import '../formula.dart';

class HscPhysics2Database {
  static final List<Formula> hscPhysics2Formulas = [
    // ========== CHAPTER 1: THERMODYNAMICS ==========
    Formula(
      id: 'hsc2_temp_scales',
      name: 'Temperature Scales Relation',
      variables: ['C', 'F', 'K'],
      equations: {'C': '5*(F-32)/9', 'F': '(9*C/5)+32', 'K': 'C+273'},
    ),
    Formula(
      id: 'hsc2_thermometric_temp',
      name: 'Thermometric Property Temp',
      variables: ['theta', 'X_theta', 'X_ice', 'X_steam'],
      equations: {
        'theta': '((X_theta-X_ice)/(X_steam-X_ice))*100',
        'X_theta': 'X_ice+(theta/100)*(X_steam-X_ice)',
      },
    ),
    Formula(
      id: 'hsc2_resistance_thermometer',
      name: 'Resistance Thermometer Temp',
      variables: ['theta', 'R_theta', 'R_0', 'R_100'],
      equations: {
        'theta': '((R_theta-R_0)/(R_100-R_0))*100',
        'R_theta': 'R_0+(theta/100)*(R_100-R_0)',
      },
    ),
    Formula(
      id: 'hsc2_joule_mech_eq',
      name: "Joule's Mechanical Equivalent (W = JH)",
      variables: ['W', 'J', 'H'],
      equations: {'W': 'J*H', 'J': 'W/H', 'H': 'W/J'},
    ),
    Formula(
      id: 'hsc2_first_law',
      name: 'First Law of Thermodynamics',
      variables: ['dQ', 'dU', 'dW'],
      equations: {'dQ': 'dU+dW', 'dU': 'dQ-dW', 'dW': 'dQ-dU'},
    ),
    Formula(
      id: 'hsc2_gas_work_diff',
      name: 'Differential Gas Work (dW = PdV)',
      variables: ['dW', 'P', 'dV'],
      equations: {'dW': 'P*dV', 'P': 'dW/dV', 'dV': 'dW/P'},
    ),
    Formula(
      id: 'hsc2_isobaric_first_law',
      name: 'First Law (Isobaric)',
      variables: ['dQ', 'dU', 'P', 'V2', 'V1'],
      equations: {'dQ': 'dU+P*(V2-V1)', 'dU': 'dQ-P*(V2-V1)'},
    ),
    Formula(
      id: 'hsc2_isothermal_work',
      name: 'Isothermal Work (W = nRT ln(Vf/Vi))',
      variables: ['W', 'n', 'T', 'Vi', 'Vf'],
      equations: {
        'W': 'n*8.314*T*ln(Vf/Vi)',
        'T': 'W/(n*8.314*ln(Vf/Vi))',
        'Vf': 'Vi*2.71828^(W/(n*8.314*T))',
        'Vi': 'Vf*2.71828^(-W/(n*8.314*T))',
      },
    ),
    Formula(
      id: 'hsc2_molar_heat',
      name: 'Molar Specific Heat (C = dQ/(n dT))',
      variables: ['C', 'dQ', 'n', 'dT'],
      equations: {
        'C': 'dQ/(n*dT)',
        'dQ': 'C*n*dT',
        'n': 'dQ/(C*dT)',
        'dT': 'dQ/(C*n)',
      },
    ),
    Formula(
      id: 'hsc2_mayers_relation',
      name: "Mayer's Relation (Cp - Cv = R)",
      variables: ['Cp', 'Cv', 'R'],
      equations: {'Cp': 'Cv+8.314', 'Cv': 'Cp-8.314', 'R': 'Cp-Cv'},
    ),
    Formula(
      id: 'hsc2_gamma_ratio',
      name: 'Gamma Ratio (γ = Cp/Cv)',
      variables: ['gamma', 'Cp', 'Cv'],
      equations: {'gamma': 'Cp/Cv', 'Cp': 'gamma*Cv', 'Cv': 'Cp/gamma'},
    ),
    Formula(
      id: 'hsc2_cv_gamma',
      name: 'Cv from Gamma (Cv = R/(γ-1))',
      variables: ['Cv', 'R', 'gamma'],
      equations: {'Cv': '8.314/(gamma-1)', 'gamma': '8.314/Cv+1'},
    ),
    Formula(
      id: 'hsc2_adiabatic_eq_pv',
      name: 'Adiabatic Equation (P1V1^γ = P2V2^γ)',
      variables: ['P1', 'V1', 'P2', 'V2', 'gamma'],
      equations: {
        'P1': 'P2*(V2/V1)^gamma',
        'V1': 'V2*(P2/P1)^(1/gamma)',
        'P2': 'P1*(V1/V2)^gamma',
        'V2': 'V1*(P1/P2)^(1/gamma)',
      },
    ),
    Formula(
      id: 'hsc2_adiabatic_eq_tv',
      name: 'Adiabatic Equation (T1V1^(γ-1) = T2V2^(γ-1))',
      variables: ['T1', 'V1', 'T2', 'V2', 'gamma'],
      equations: {
        'T1': 'T2*(V2/V1)^(gamma-1)',
        'T2': 'T1*(V1/V2)^(gamma-1)',
        'V1': 'V2*(T2/T1)^(1/(gamma-1))',
        'V2': 'V1*(T1/T2)^(1/(gamma-1))',
      },
    ),
    Formula(
      id: 'hsc2_adiabatic_eq_tp',
      name: 'Adiabatic Equation (T^γ P^(1-γ) = const)',
      variables: ['T1', 'P1', 'T2', 'P2', 'gamma'],
      equations: {
        'T1': 'T2*(P2/P1)^((gamma-1)/gamma)',
        'T2': 'T1*(P1/P2)^((gamma-1)/gamma)',
        'P1': 'P2*(T2/T1)^(gamma/(gamma-1))',
        'P2': 'P1*(T1/T2)^(gamma/(gamma-1))',
      },
    ),
    Formula(
      id: 'hsc2_heat_engine_eff',
      name: 'Heat Engine Efficiency (η = 1 - Q2/Q1)',
      variables: ['eta', 'Q1', 'Q2'],
      equations: {'eta': '1-Q2/Q1', 'Q1': 'Q2/(1-eta)', 'Q2': 'Q1*(1-eta)'},
    ),
    Formula(
      id: 'hsc2_carnot_q_t',
      name: 'Carnot Q/T Relation (Q1/T1 = Q2/T2)',
      variables: ['Q1', 'T1', 'Q2', 'T2'],
      equations: {
        'Q1': 'Q2*T1/T2',
        'T1': 'Q1*T2/Q2',
        'Q2': 'Q1*T2/T1',
        'T2': 'Q2*T1/Q1',
      },
    ),
    Formula(
      id: 'hsc2_carnot_eff',
      name: 'Carnot Efficiency (η = 1 - T2/T1)',
      variables: ['eta', 'T1', 'T2'],
      equations: {'eta': '1-T2/T1', 'T1': 'T2/(1-eta)', 'T2': 'T1*(1-eta)'},
    ),
    Formula(
      id: 'hsc2_cop_fridge',
      name: 'COP of Refrigerator (K = Q2/W)',
      variables: ['K', 'Q2', 'W'],
      equations: {'K': 'Q2/W', 'Q2': 'K*W', 'W': 'Q2/K'},
    ),
    Formula(
      id: 'hsc2_cop_temps',
      name: 'COP from Temps (K = T2/(T1-T2))',
      variables: ['K', 'T1', 'T2'],
      equations: {'K': 'T2/(T1-T2)', 'T1': 'T2/K+T2', 'T2': 'K*T1/(1+K)'},
    ),
    Formula(
      id: 'hsc2_entropy_diff',
      name: 'Entropy Change (dS = dQ/T)',
      variables: ['dS', 'dQ', 'T'],
      equations: {'dS': 'dQ/T', 'dQ': 'dS*T', 'T': 'dQ/dS'},
    ),
    Formula(
      id: 'hsc2_entropy_temp',
      name: 'Entropy Temp Change (dS = ms ln(T2/T1))',
      variables: ['dS', 'm', 's', 'T1', 'T2'],
      equations: {
        'dS': 'm*s*ln(T2/T1)',
        'T2': 'T1*2.71828^(dS/(m*s))',
        'T1': 'T2*2.71828^(-dS/(m*s))',
      },
    ),
    Formula(
      id: 'hsc2_entropy_phase',
      name: 'Entropy Phase Change (dS = mL/T)',
      variables: ['dS', 'm', 'L', 'T'],
      equations: {'dS': 'm*L/T', 'm': 'dS*T/L', 'L': 'dS*T/m', 'T': 'm*L/dS'},
    ),

    // ========== CHAPTER 2: STATIC ELECTRICITY ==========
    Formula(
      id: 'hsc2_coulomb_vacuum',
      name: "Coulomb's Law (Vacuum)",
      variables: ['F', 'q1', 'q2', 'r'],
      equations: {
        'F': '8.99e9*q1*q2/(r^2)',
        'q1': 'F*r^2/(8.99e9*q2)',
        'q2': 'F*r^2/(8.99e9*q1)',
        'r': 'sqrt(8.99e9*q1*q2/F)',
      },
    ),
    Formula(
      id: 'hsc2_coulomb_medium',
      name: "Coulomb's Law (Medium)",
      variables: ['F', 'q1', 'q2', 'r', 'K'],
      equations: {
        'F': '8.99e9*q1*q2/(K*r^2)',
        'K': '8.99e9*q1*q2/(F*r^2)',
        'r': 'sqrt(8.99e9*q1*q2/(K*F))',
      },
    ),
    Formula(
      id: 'hsc2_dielectric_const',
      name: 'Dielectric Constant (K = F0/F)',
      variables: ['K', 'F0', 'F'],
      equations: {'K': 'F0/F', 'F0': 'K*F', 'F': 'F0/K'},
    ),
    Formula(
      id: 'hsc2_e_field_def',
      name: 'Electric Field (E = F/q)',
      variables: ['E', 'F', 'q'],
      equations: {'E': 'F/q', 'F': 'E*q', 'q': 'F/E'},
    ),
    Formula(
      id: 'hsc2_e_field_point',
      name: 'E from Point Charge (E = kq/r²)',
      variables: ['E', 'q', 'r', 'K'],
      equations: {
        'E': '8.99e9*q/(K*r^2)',
        'q': 'E*K*r^2/8.99e9',
        'r': 'sqrt(8.99e9*q/(K*E))',
        'K': '8.99e9*q/(E*r^2)',
      },
    ),
    Formula(
      id: 'hsc2_e_field_lines',
      name: 'Number of Field Lines (N = q/ε₀)',
      variables: ['N', 'q'],
      equations: {'N': 'q/8.854e-12', 'q': 'N*8.854e-12'},
    ),
    Formula(
      id: 'hsc2_potential_def',
      name: 'Electric Potential (V = W/q)',
      variables: ['V', 'W', 'q'],
      equations: {'V': 'W/q', 'W': 'V*q', 'q': 'W/V'},
    ),
    Formula(
      id: 'hsc2_potential_point',
      name: 'Potential Point Charge (V = kq/r)',
      variables: ['V', 'q', 'r'],
      equations: {'V': '8.99e9*q/r', 'q': 'V*r/8.99e9', 'r': '8.99e9*q/V'},
    ),
    Formula(
      id: 'hsc2_e_potential_grad',
      name: 'E from Potential Gradient (E = -dV/dr)',
      variables: ['E', 'dV', 'dr'],
      equations: {'E': '-dV/dr', 'dV': '-E*dr', 'dr': '-dV/E'},
    ),
    Formula(
      id: 'hsc2_pe_two_charges',
      name: 'PE of Two Charges (U = kq1q2/r)',
      variables: ['U', 'q1', 'q2', 'r'],
      equations: {
        'U': '8.99e9*q1*q2/r',
        'q1': 'U*r/(8.99e9*q2)',
        'q2': 'U*r/(8.99e9*q1)',
        'r': '8.99e9*q1*q2/U',
      },
    ),
    Formula(
      id: 'hsc2_ev_to_joule',
      name: 'eV to Joule (1 eV = 1.6e-19 J)',
      variables: ['E_eV', 'E_J'],
      equations: {'E_eV': 'E_J/1.6e-19', 'E_J': 'E_eV*1.6e-19'},
    ),
    Formula(
      id: 'hsc2_dipole_moment',
      name: 'Dipole Moment (p = q·2l)',
      variables: ['p', 'q', 'l'],
      equations: {'p': 'q*2*l', 'q': 'p/(2*l)', 'l': 'p/(2*q)'},
    ),
    Formula(
      id: 'hsc2_dipole_torque',
      name: 'Torque on Dipole (τ = pEsinθ)',
      variables: ['tau', 'p', 'E', 'theta'],
      equations: {
        'tau': 'p*E*sin(theta)',
        'p': 'tau/(E*sin(theta))',
        'E': 'tau/(p*sin(theta))',
        'theta': 'asin(tau/(p*E))',
      },
    ),
    Formula(
      id: 'hsc2_dipole_work',
      name: 'Work Rotating Dipole',
      variables: ['W', 'p', 'E', 'theta1', 'theta2'],
      equations: {
        'W': '-p*E*(cos(theta2)-cos(theta1))',
        'p': 'W/(-E*(cos(theta2)-cos(theta1)))',
      },
    ),
    Formula(
      id: 'hsc2_dipole_pe',
      name: 'PE of Dipole (U = -pEcosθ)',
      variables: ['U', 'p', 'E', 'theta'],
      equations: {
        'U': '-p*E*cos(theta)',
        'p': '-U/(E*cos(theta))',
        'E': '-U/(p*cos(theta))',
        'theta': 'acos(-U/(p*E))',
      },
    ),
    Formula(
      id: 'hsc2_dipole_axial_v',
      name: 'Dipole Axial Potential',
      variables: ['V', 'p', 'r', 'l'],
      equations: {'V': '8.99e9*p/(r^2-l^2)', 'p': 'V*(r^2-l^2)/8.99e9'},
    ),
    Formula(
      id: 'hsc2_dipole_axial_e',
      name: 'Dipole Axial Field',
      variables: ['E', 'p', 'r', 'l'],
      equations: {
        'E': '8.99e9*2*p*r/((r^2-l^2)^2)',
        'p': 'E*(r^2-l^2)^2/(8.99e9*2*r)',
      },
    ),
    Formula(
      id: 'hsc2_dipole_eq_e',
      name: 'Dipole Equatorial Field',
      variables: ['E', 'p', 'r', 'l'],
      equations: {
        'E': '8.99e9*p/((r^2+l^2)^1.5)',
        'p': 'E*(r^2+l^2)^1.5/8.99e9',
      },
    ),
    Formula(
      id: 'hsc2_capacitance_def',
      name: 'Capacitance (C = Q/V)',
      variables: ['C', 'Q', 'V'],
      equations: {'C': 'Q/V', 'Q': 'C*V', 'V': 'Q/C'},
    ),
    Formula(
      id: 'hsc2_sphere_capacitance',
      name: 'Spherical Capacitance (C = 4πε₀kr)',
      variables: ['C', 'r', 'K'],
      equations: {
        'C': '4*3.14159*8.854e-12*K*r',
        'r': 'C/(4*3.14159*8.854e-12*K)',
        'K': 'C/(4*3.14159*8.854e-12*r)',
      },
    ),
    Formula(
      id: 'hsc2_sphere_surface_potential',
      name: 'Sphere Surface Potential',
      variables: ['V', 'Q', 'r'],
      equations: {'V': '8.99e9*Q/r', 'Q': 'V*r/8.99e9', 'r': '8.99e9*Q/V'},
    ),
    Formula(
      id: 'hsc2_parallel_plate_cap',
      name: 'Parallel Plate Capacitance',
      variables: ['C', 'A', 'd', 'K'],
      equations: {
        'C': '8.854e-12*K*A/d',
        'A': 'C*d/(8.854e-12*K)',
        'd': '8.854e-12*K*A/C',
        'K': 'C*d/(8.854e-12*A)',
      },
    ),
    Formula(
      id: 'hsc2_surface_charge_density',
      name: 'Surface Charge Density (σ = Q/A)',
      variables: ['sigma', 'Q', 'A'],
      equations: {'sigma': 'Q/A', 'Q': 'sigma*A', 'A': 'Q/sigma'},
    ),
    Formula(
      id: 'hsc2_capacitors_series',
      name: 'Capacitors in Series (Cs)',
      variables: ['Cs', 'C1', 'C2'],
      equations: {
        'Cs': 'C1*C2/(C1+C2)',
        'C1': 'Cs*C2/(C2-Cs)',
        'C2': 'Cs*C1/(C1-Cs)',
      },
    ),
    Formula(
      id: 'hsc2_capacitors_parallel',
      name: 'Capacitors in Parallel (Cp)',
      variables: ['Cp', 'C1', 'C2'],
      equations: {'Cp': 'C1+C2', 'C1': 'Cp-C2', 'C2': 'Cp-C1'},
    ),
    Formula(
      id: 'hsc2_cap_energy',
      name: 'Capacitor Energy (U = ½CV²)',
      variables: ['U', 'C', 'V'],
      equations: {'U': '0.5*C*V^2', 'C': '2*U/(V^2)', 'V': 'sqrt(2*U/C)'},
    ),
    Formula(
      id: 'hsc2_energy_density',
      name: 'Energy Density (u = ½ε₀E²)',
      variables: ['u', 'E', 'K'],
      equations: {
        'u': '0.5*8.854e-12*K*E^2',
        'E': 'sqrt(2*u/(8.854e-12*K))',
        'K': '2*u/(8.854e-12*E^2)',
      },
    ),
    Formula(
      id: 'hsc2_electric_flux',
      name: 'Electric Flux (Φ = EAcosθ)',
      variables: ['phi', 'E', 'A', 'theta'],
      equations: {
        'phi': 'E*A*cos(theta)',
        'E': 'phi/(A*cos(theta))',
        'A': 'phi/(E*cos(theta))',
        'theta': 'acos(phi/(E*A))',
      },
    ),
    Formula(
      id: 'hsc2_gauss_law',
      name: "Gauss's Law (Φ = q/ε₀)",
      variables: ['phi', 'q'],
      equations: {'phi': 'q/8.854e-12', 'q': 'phi*8.854e-12'},
    ),
    Formula(
      id: 'hsc2_line_charge_field',
      name: 'E from Line Charge (E = λ/(2πε₀r))',
      variables: ['E', 'lambda', 'r'],
      equations: {
        'E': 'lambda/(2*3.14159*8.854e-12*r)',
        'lambda': 'E*2*3.14159*8.854e-12*r',
        'r': 'lambda/(2*3.14159*8.854e-12*E)',
      },
    ),
    Formula(
      id: 'hsc2_linear_charge_density',
      name: 'Linear Charge Density (λ = q/L)',
      variables: ['lambda', 'q', 'L'],
      equations: {'lambda': 'q/L', 'q': 'lambda*L', 'L': 'q/lambda'},
    ),

    // ========== CHAPTER 3: CURRENT ELECTRICITY ==========
    Formula(
      id: 'hsc2_resistance_temp',
      name: 'Resistance at Temp t (Rt = R0(1+αt))',
      variables: ['Rt', 'R0', 'alpha', 't'],
      equations: {
        'Rt': 'R0*(1+alpha*t)',
        'R0': 'Rt/(1+alpha*t)',
        'alpha': '(Rt/R0-1)/t',
        't': '(Rt/R0-1)/alpha',
      },
    ),
    Formula(
      id: 'hsc2_temp_coeff',
      name: 'Temp Coefficient (α = (Rt-R0)/(R0t))',
      variables: ['alpha', 'Rt', 'R0', 't'],
      equations: {
        'alpha': '(Rt-R0)/(R0*t)',
        'Rt': 'R0*(1+alpha*t)',
        'R0': 'Rt/(1+alpha*t)',
        't': '(Rt-R0)/(R0*alpha)',
      },
    ),
    Formula(
      id: 'hsc2_joule_heating',
      name: "Joule's Heating (H = I²Rt)",
      variables: ['H', 'I', 'R', 't'],
      equations: {
        'H': 'I^2*R*t',
        'I': 'sqrt(H/(R*t))',
        'R': 'H/(I^2*t)',
        't': 'H/(I^2*R)',
      },
    ),
    Formula(
      id: 'hsc2_drift_velocity',
      name: 'Drift Velocity (I = nAve)',
      variables: ['I', 'n', 'A', 'v'],
      equations: {
        'I': 'n*A*v*1.6e-19',
        'n': 'I/(A*v*1.6e-19)',
        'A': 'I/(n*v*1.6e-19)',
        'v': 'I/(n*A*1.6e-19)',
      },
    ),
    Formula(
      id: 'hsc2_current_density',
      name: 'Current Density (j = I/A)',
      variables: ['j', 'I', 'A'],
      equations: {'j': 'I/A', 'I': 'j*A', 'A': 'I/j'},
    ),
    Formula(
      id: 'hsc2_resistivity',
      name: 'Resistivity (R = ρl/A)',
      variables: ['R', 'rho', 'l', 'A'],
      equations: {
        'R': 'rho*l/A',
        'rho': 'R*A/l',
        'l': 'R*A/rho',
        'A': 'rho*l/R',
      },
    ),
    Formula(
      id: 'hsc2_resistors_series',
      name: 'Resistors in Series',
      variables: ['Rs', 'R1', 'R2'],
      equations: {'Rs': 'R1+R2', 'R1': 'Rs-R2', 'R2': 'Rs-R1'},
    ),
    Formula(
      id: 'hsc2_resistors_parallel',
      name: 'Resistors in Parallel',
      variables: ['Rp', 'R1', 'R2'],
      equations: {
        'Rp': 'R1*R2/(R1+R2)',
        'R1': 'Rp*R2/(R2-Rp)',
        'R2': 'Rp*R1/(R1-Rp)',
      },
    ),
    Formula(
      id: 'hsc2_circuit_current',
      name: 'Circuit Current (I = E/(R+r))',
      variables: ['I', 'E', 'R', 'r'],
      equations: {'I': 'E/(R+r)', 'E': 'I*(R+r)', 'R': 'E/I-r', 'r': 'E/I-R'},
    ),
    Formula(
      id: 'hsc2_terminal_pd',
      name: 'Terminal PD (E = V + Ir)',
      variables: ['E', 'V', 'I', 'r'],
      equations: {'E': 'V+I*r', 'V': 'E-I*r', 'I': '(E-V)/r', 'r': '(E-V)/I'},
    ),
    Formula(
      id: 'hsc2_max_power',
      name: 'Max Power Transfer (P = E²/4r)',
      variables: ['P', 'E', 'r'],
      equations: {'P': 'E^2/(4*r)', 'E': 'sqrt(4*P*r)', 'r': 'E^2/(4*P)'},
    ),
    Formula(
      id: 'hsc2_cells_series',
      name: 'Cells in Series (Is = nE/(R+nr))',
      variables: ['Is', 'n', 'E', 'R', 'r'],
      equations: {'Is': 'n*E/(R+n*r)', 'E': 'Is*(R+n*r)/n', 'R': 'n*E/Is-n*r'},
    ),
    Formula(
      id: 'hsc2_cells_parallel',
      name: 'Cells in Parallel (Ip = E/(R+r/n))',
      variables: ['Ip', 'E', 'R', 'r', 'n'],
      equations: {'Ip': 'E/(R+r/n)', 'E': 'Ip*(R+r/n)', 'R': 'E/Ip-r/n'},
    ),
    Formula(
      id: 'hsc2_cells_mixed',
      name: 'Mixed Cells (I = mnE/(mR+nr))',
      variables: ['I', 'm', 'n', 'E', 'R', 'r'],
      equations: {
        'I': 'm*n*E/(m*R+n*r)',
        'E': 'I*(m*R+n*r)/(m*n)',
        'R': 'm*n*E/(m*I)-n*r/m',
      },
    ),
    Formula(
      id: 'hsc2_wheatstone',
      name: 'Wheatstone Bridge (P/Q = R/S)',
      variables: ['P', 'Q', 'R', 'S'],
      equations: {'P': 'Q*R/S', 'Q': 'P*S/R', 'R': 'P*S/Q', 'S': 'Q*R/P'},
    ),
    Formula(
      id: 'hsc2_galvanometer_shunt',
      name: 'Galvanometer Current (Ig)',
      variables: ['Ig', 'S', 'G', 'I'],
      equations: {
        'Ig': 'S*I/(G+S)',
        'S': 'Ig*G/(I-Ig)',
        'G': 'S*(I-Ig)/Ig',
        'I': 'Ig*(G+S)/S',
      },
    ),
    Formula(
      id: 'hsc2_shunt_current',
      name: 'Shunt Current (Is)',
      variables: ['Is', 'G', 'S', 'I'],
      equations: {
        'Is': 'G*I/(G+S)',
        'G': 'Is*S/(I-Is)',
        'S': 'G*(I-Is)/Is',
        'I': 'Is*(G+S)/G',
      },
    ),
    Formula(
      id: 'hsc2_shunt_resistance',
      name: 'Shunt Resistance (S = IgG/(I-Ig))',
      variables: ['S', 'Ig', 'G', 'I'],
      equations: {
        'S': 'Ig*G/(I-Ig)',
        'Ig': 'S*I/(G+S)',
        'G': 'S*(I-Ig)/Ig',
        'I': 'Ig*(G+S)/S',
      },
    ),
    Formula(
      id: 'hsc2_meter_bridge',
      name: 'Meter Bridge (X = R l/(100-l))',
      variables: ['X', 'R', 'l'],
      equations: {'X': 'R*l/(100-l)', 'R': 'X*(100-l)/l', 'l': '100*X/(R+X)'},
    ),
    Formula(
      id: 'hsc2_potentiometer_emf',
      name: 'Potentiometer EMF (E1/E2 = l1/l2)',
      variables: ['E1', 'E2', 'l1', 'l2'],
      equations: {
        'E1': 'E2*l1/l2',
        'E2': 'E1*l2/l1',
        'l1': 'E1*l2/E2',
        'l2': 'E2*l1/E1',
      },
    ),

    // ========== CHAPTER 4: MAGNETIC EFFECT ==========
    Formula(
      id: 'hsc2_biot_savart',
      name: 'Biot-Savart Law (dB)',
      variables: ['dB', 'i', 'dl', 'alpha', 'r'],
      equations: {
        'dB': '1e-7*i*dl*sin(alpha)/(r^2)',
        'i': 'dB*r^2/(1e-7*dl*sin(alpha))',
        'r': 'sqrt(1e-7*i*dl*sin(alpha)/dB)',
        'alpha': 'asin(dB*r^2/(1e-7*i*dl))',
      },
    ),
    Formula(
      id: 'hsc2_b_circular_coil',
      name: 'B at Center of Coil',
      variables: ['B', 'n', 'i', 'r'],
      equations: {
        'B': '2e-7*3.14159*n*i/r',
        'n': 'B*r/(2e-7*3.14159*i)',
        'i': 'B*r/(2e-7*3.14159*n)',
        'r': '2e-7*3.14159*n*i/B',
      },
    ),
    Formula(
      id: 'hsc2_b_straight_wire',
      name: 'B from Straight Wire',
      variables: ['B', 'i', 'r'],
      equations: {'B': '2e-7*i/r', 'i': 'B*r/2e-7', 'r': '2e-7*i/B'},
    ),
    Formula(
      id: 'hsc2_b_solenoid',
      name: 'B inside Solenoid (B = μ₀ni)',
      variables: ['B', 'n', 'i'],
      equations: {
        'B': '4*3.14159e-7*n*i',
        'n': 'B/(4*3.14159e-7*i)',
        'i': 'B/(4*3.14159e-7*n)',
      },
    ),
    Formula(
      id: 'hsc2_lorentz_force',
      name: 'Lorentz Force (F = qvBsinθ)',
      variables: ['F', 'q', 'v', 'B', 'theta'],
      equations: {
        'F': 'q*v*B*sin(theta)',
        'q': 'F/(v*B*sin(theta))',
        'v': 'F/(q*B*sin(theta))',
        'B': 'F/(q*v*sin(theta))',
        'theta': 'asin(F/(q*v*B))',
      },
    ),
    Formula(
      id: 'hsc2_force_wire',
      name: 'Force on Wire (F = IlBsinθ)',
      variables: ['F', 'I', 'l', 'B', 'theta'],
      equations: {
        'F': 'I*l*B*sin(theta)',
        'I': 'F/(l*B*sin(theta))',
        'l': 'F/(I*B*sin(theta))',
        'B': 'F/(I*l*sin(theta))',
        'theta': 'asin(F/(I*l*B))',
      },
    ),
    Formula(
      id: 'hsc2_force_parallel_wires',
      name: 'Force Between Parallel Wires',
      variables: ['F', 'I1', 'I2', 'd', 'l'],
      equations: {
        'F': '2e-7*I1*I2*l/d',
        'I1': 'F*d/(2e-7*I2*l)',
        'I2': 'F*d/(2e-7*I1*l)',
        'd': '2e-7*I1*I2*l/F',
        'l': 'F*d/(2e-7*I1*I2)',
      },
    ),
    Formula(
      id: 'hsc2_torque_loop',
      name: 'Torque on Loop (τ = NIABsinθ)',
      variables: ['tau', 'N', 'I', 'A', 'B', 'theta'],
      equations: {
        'tau': 'N*I*A*B*sin(theta)',
        'N': 'tau/(I*A*B*sin(theta))',
        'I': 'tau/(N*A*B*sin(theta))',
        'A': 'tau/(N*I*B*sin(theta))',
        'B': 'tau/(N*I*A*sin(theta))',
        'theta': 'asin(tau/(N*I*A*B))',
      },
    ),
    Formula(
      id: 'hsc2_magnetic_moment',
      name: 'Magnetic Moment (M = NIA)',
      variables: ['M', 'N', 'I', 'A'],
      equations: {'M': 'N*I*A', 'N': 'M/(I*A)', 'I': 'M/(N*A)', 'A': 'M/(N*I)'},
    ),
    Formula(
      id: 'hsc2_hall_voltage',
      name: 'Hall Voltage (VH = BI/(nqt))',
      variables: ['VH', 'B', 'I', 'n', 't'],
      equations: {
        'VH': 'B*I/(n*1.6e-19*t)',
        'B': 'VH*n*1.6e-19*t/I',
        'I': 'VH*n*1.6e-19*t/B',
        'n': 'B*I/(VH*1.6e-19*t)',
        't': 'B*I/(VH*n*1.6e-19)',
      },
    ),
    Formula(
      id: 'hsc2_hall_field',
      name: 'Hall Electric Field (EH = vBsinθ)',
      variables: ['EH', 'v', 'B', 'theta'],
      equations: {
        'EH': 'v*B*sin(theta)',
        'v': 'EH/(B*sin(theta))',
        'B': 'EH/(v*sin(theta))',
        'theta': 'asin(EH/(v*B))',
      },
    ),
    Formula(
      id: 'hsc2_magnetic_intensity',
      name: 'Magnetic Intensity (H = B/μ)',
      variables: ['H', 'B', 'mu'],
      equations: {'H': 'B/mu', 'B': 'H*mu', 'mu': 'B/H'},
    ),
    Formula(
      id: 'hsc2_permeability',
      name: 'Magnetic Permeability (μ = B/H)',
      variables: ['mu', 'B', 'H'],
      equations: {'mu': 'B/H', 'B': 'mu*H', 'H': 'B/mu'},
    ),
    Formula(
      id: 'hsc2_relative_permeability',
      name: 'Relative Permeability (μr = μ/μ₀)',
      variables: ['mu_r', 'mu'],
      equations: {'mu_r': 'mu/(4*3.14159e-7)', 'mu': 'mu_r*4*3.14159e-7'},
    ),
    Formula(
      id: 'hsc2_magnetization',
      name: 'Intensity of Magnetization (I = M/V)',
      variables: ['I', 'M', 'V'],
      equations: {'I': 'M/V', 'M': 'I*V', 'V': 'M/I'},
    ),
    Formula(
      id: 'hsc2_susceptibility',
      name: 'Magnetic Susceptibility (χ = I/H)',
      variables: ['chi', 'I', 'H'],
      equations: {'chi': 'I/H', 'I': 'chi*H', 'H': 'I/chi'},
    ),
    Formula(
      id: 'hsc2_mu_chi_relation',
      name: 'Relation μr = 1 + χ',
      variables: ['mu_r', 'chi'],
      equations: {'mu_r': '1+chi', 'chi': 'mu_r-1'},
    ),
    Formula(
      id: 'hsc2_earth_horizontal',
      name: "Earth's Horizontal Component (H = Bcosδ)",
      variables: ['H', 'B', 'delta'],
      equations: {
        'H': 'B*cos(delta)',
        'B': 'H/cos(delta)',
        'delta': 'acos(H/B)',
      },
    ),
    Formula(
      id: 'hsc2_earth_vertical',
      name: "Earth's Vertical Component (V = Bsinδ)",
      variables: ['V', 'B', 'delta'],
      equations: {
        'V': 'B*sin(delta)',
        'B': 'V/sin(delta)',
        'delta': 'asin(V/B)',
      },
    ),
    Formula(
      id: 'hsc2_earth_total',
      name: "Earth's Total Field (B = √(H²+V²))",
      variables: ['B', 'H', 'V'],
      equations: {
        'B': 'sqrt(H^2+V^2)',
        'H': 'sqrt(B^2-V^2)',
        'V': 'sqrt(B^2-H^2)',
      },
    ),
    Formula(
      id: 'hsc2_dip_angle',
      name: 'Dip Angle (tanδ = V/H)',
      variables: ['delta', 'V', 'H'],
      equations: {
        'delta': 'atan(V/H)',
        'V': 'H*tan(delta)',
        'H': 'V/tan(delta)',
      },
    ),
    Formula(
      id: 'hsc2_magnetic_flux',
      name: 'Magnetic Flux (Φ = BAcosθ)',
      variables: ['phi', 'B', 'A', 'theta'],
      equations: {
        'phi': 'B*A*cos(theta)',
        'B': 'phi/(A*cos(theta))',
        'A': 'phi/(B*cos(theta))',
        'theta': 'acos(phi/(B*A))',
      },
    ),
    Formula(
      id: 'hsc2_charged_particle_ke',
      name: 'KE of Charged Particle (K = ½mv²)',
      variables: ['K', 'm', 'v'],
      equations: {'K': '0.5*m*v^2', 'm': '2*K/(v^2)', 'v': 'sqrt(2*K/m)'},
    ),
    Formula(
      id: 'hsc2_radius_circular_path',
      name: 'Radius of Circular Path (r = mv/qB)',
      variables: ['r', 'm', 'v', 'q', 'B'],
      equations: {
        'r': 'm*v/(q*B)',
        'm': 'r*q*B/v',
        'v': 'r*q*B/m',
        'q': 'm*v/(r*B)',
        'B': 'm*v/(r*q)',
      },
    ),

    // ========== CHAPTER 5: EMI & AC ==========
    Formula(
      id: 'hsc2_flux_emi',
      name: 'Magnetic Flux (Φ = BAcosθ)',
      variables: ['phi', 'B', 'A', 'theta'],
      equations: {
        'phi': 'B*A*cos(theta)',
        'B': 'phi/(A*cos(theta))',
        'A': 'phi/(B*cos(theta))',
        'theta': 'acos(phi/(B*A))',
      },
    ),
    Formula(
      id: 'hsc2_faraday_single',
      name: "Faraday's Law (E = -dΦ/dt)",
      variables: ['E', 'dphi', 'dt'],
      equations: {'E': '-dphi/dt', 'dphi': '-E*dt', 'dt': '-dphi/E'},
    ),
    Formula(
      id: 'hsc2_faraday_n_turns',
      name: "Faraday's Law N Turns (E = -N dΦ/dt)",
      variables: ['E', 'N', 'dphi', 'dt'],
      equations: {
        'E': '-N*dphi/dt',
        'N': '-E*dt/dphi',
        'dphi': '-E*dt/N',
        'dt': '-N*dphi/E',
      },
    ),
    Formula(
      id: 'hsc2_avg_induced_emf',
      name: 'Average Induced EMF',
      variables: ['E_avg', 'N', 'dphi', 'dt'],
      equations: {
        'E_avg': '-N*dphi/dt',
        'N': '-E_avg*dt/dphi',
        'dphi': '-E_avg*dt/N',
        'dt': '-N*dphi/E_avg',
      },
    ),
    Formula(
      id: 'hsc2_induced_current',
      name: 'Induced Current (I = E/R)',
      variables: ['I', 'E', 'R'],
      equations: {'I': 'E/R', 'E': 'I*R', 'R': 'E/I'},
    ),
    Formula(
      id: 'hsc2_induced_charge',
      name: 'Induced Charge (q = NΔΦ/R)',
      variables: ['q', 'N', 'dphi', 'R'],
      equations: {
        'q': 'N*dphi/R',
        'N': 'q*R/dphi',
        'dphi': 'q*R/N',
        'R': 'N*dphi/q',
      },
    ),
    Formula(
      id: 'hsc2_self_inductance_flux',
      name: 'Self Inductance Flux (NΦ = LI)',
      variables: ['N', 'phi', 'L', 'I'],
      equations: {
        'N': 'L*I/phi',
        'phi': 'L*I/N',
        'L': 'N*phi/I',
        'I': 'N*phi/L',
      },
    ),
    Formula(
      id: 'hsc2_self_induced_emf',
      name: 'Self Induced EMF (E = -L dI/dt)',
      variables: ['E', 'L', 'dI', 'dt'],
      equations: {
        'E': '-L*dI/dt',
        'L': '-E*dt/dI',
        'dI': '-E*dt/L',
        'dt': '-L*dI/E',
      },
    ),
    Formula(
      id: 'hsc2_solenoid_self_inductance',
      name: 'Solenoid Self Inductance',
      variables: ['L', 'N', 'A', 'l'],
      equations: {
        'L': '4*3.14159e-7*N^2*A/l',
        'N': 'sqrt(L*l/(4*3.14159e-7*A))',
        'A': 'L*l/(4*3.14159e-7*N^2)',
        'l': '4*3.14159e-7*N^2*A/L',
      },
    ),
    Formula(
      id: 'hsc2_inductor_energy',
      name: 'Inductor Energy (U = ½LI²)',
      variables: ['U', 'L', 'I'],
      equations: {'U': '0.5*L*I^2', 'L': '2*U/(I^2)', 'I': 'sqrt(2*U/L)'},
    ),
    Formula(
      id: 'hsc2_mutual_inductance_flux',
      name: 'Mutual Inductance Flux',
      variables: ['Ns', 'phis', 'M', 'Ip'],
      equations: {
        'Ns': 'M*Ip/phis',
        'phis': 'M*Ip/Ns',
        'M': 'Ns*phis/Ip',
        'Ip': 'Ns*phis/M',
      },
    ),
    Formula(
      id: 'hsc2_mutual_induced_emf',
      name: 'Mutual Induced EMF',
      variables: ['Es', 'M', 'dIp', 'dt'],
      equations: {
        'Es': '-M*dIp/dt',
        'M': '-Es*dt/dIp',
        'dIp': '-Es*dt/M',
        'dt': '-M*dIp/Es',
      },
    ),
    Formula(
      id: 'hsc2_mutual_inductance_ideal',
      name: 'Mutual Inductance Ideal (M = √(L1L2))',
      variables: ['M', 'L1', 'L2'],
      equations: {'M': 'sqrt(L1*L2)', 'L1': 'M^2/L2', 'L2': 'M^2/L1'},
    ),
    Formula(
      id: 'hsc2_transformer_voltage',
      name: 'Transformer Voltage Ratio',
      variables: ['Es', 'Ep', 'ns', 'np'],
      equations: {
        'Es': 'Ep*ns/np',
        'Ep': 'Es*np/ns',
        'ns': 'Es*np/Ep',
        'np': 'Ep*ns/Es',
      },
    ),
    Formula(
      id: 'hsc2_transformer_current',
      name: 'Transformer Current Ratio',
      variables: ['Ip', 'Is', 'ns', 'np'],
      equations: {
        'Ip': 'Is*ns/np',
        'Is': 'Ip*np/ns',
        'ns': 'Ip*np/Is',
        'np': 'Is*ns/Ip',
      },
    ),
    Formula(
      id: 'hsc2_transformer_resistance',
      name: 'Transformer Resistance Ratio',
      variables: ['Rs', 'Rp', 'ns', 'np'],
      equations: {
        'Rs': 'Rp*(ns/np)^2',
        'Rp': 'Rs*(np/ns)^2',
        'ns': 'np*sqrt(Rs/Rp)',
        'np': 'ns*sqrt(Rp/Rs)',
      },
    ),
    Formula(
      id: 'hsc2_transformer_eff',
      name: 'Transformer Efficiency',
      variables: ['eta', 'Vs', 'Is', 'Vp', 'Ip'],
      equations: {
        'eta': '(Vs*Is/(Vp*Ip))*100',
        'Vs': 'eta*Vp*Ip/(100*Is)',
        'Is': 'eta*Vp*Ip/(100*Vs)',
      },
    ),
    Formula(
      id: 'hsc2_ac_emf',
      name: 'AC EMF (E = E0 sinωt)',
      variables: ['E', 'E0', 'omega', 't'],
      equations: {
        'E': 'E0*sin(omega*t)',
        'E0': 'E/sin(omega*t)',
        'omega': 'asin(E/E0)/t',
        't': 'asin(E/E0)/omega',
      },
    ),
    Formula(
      id: 'hsc2_peak_emf_coil',
      name: 'Peak EMF Rotating Coil (E0 = NABω)',
      variables: ['E0', 'N', 'A', 'B', 'omega'],
      equations: {
        'E0': 'N*A*B*omega',
        'N': 'E0/(A*B*omega)',
        'A': 'E0/(N*B*omega)',
        'B': 'E0/(N*A*omega)',
        'omega': 'E0/(N*A*B)',
      },
    ),
    Formula(
      id: 'hsc2_ac_current',
      name: 'AC Current (I = I0 sinωt)',
      variables: ['I', 'I0', 'omega', 't'],
      equations: {
        'I': 'I0*sin(omega*t)',
        'I0': 'I/sin(omega*t)',
        'omega': 'asin(I/I0)/t',
        't': 'asin(I/I0)/omega',
      },
    ),
    Formula(
      id: 'hsc2_ac_current_phase',
      name: 'AC Current with Phase (I = I0 sin(ωt+φ))',
      variables: ['I', 'I0', 'omega', 't', 'phi'],
      equations: {
        'I': 'I0*sin(omega*t+phi)',
        'I0': 'I/sin(omega*t+phi)',
        'phi': 'asin(I/I0)-omega*t',
      },
    ),
    Formula(
      id: 'hsc2_freq_period',
      name: 'Frequency and Period (f = 1/T)',
      variables: ['f', 'T'],
      equations: {'f': '1/T', 'T': '1/f'},
    ),
    Formula(
      id: 'hsc2_avg_ac_current',
      name: 'Average AC Current (Iavg = 2I0/π)',
      variables: ['Iavg', 'I0'],
      equations: {'Iavg': '2*I0/3.14159', 'I0': 'Iavg*3.14159/2'},
    ),
    Formula(
      id: 'hsc2_avg_ac_emf',
      name: 'Average AC EMF (Eavg = 2E0/π)',
      variables: ['Eavg', 'E0'],
      equations: {'Eavg': '2*E0/3.14159', 'E0': 'Eavg*3.14159/2'},
    ),
    Formula(
      id: 'hsc2_rms_current',
      name: 'RMS Current (Irms = I0/√2)',
      variables: ['Irms', 'I0'],
      equations: {'Irms': 'I0/1.41421', 'I0': 'Irms*1.41421'},
    ),
    Formula(
      id: 'hsc2_rms_voltage',
      name: 'RMS Voltage (Erms = E0/√2)',
      variables: ['Erms', 'E0'],
      equations: {'Erms': 'E0/1.41421', 'E0': 'Erms*1.41421'},
    ),
    Formula(
      id: 'hsc2_form_factor',
      name: 'Form Factor (Kf = Irms/Iavg)',
      variables: ['Kf', 'Irms', 'Iavg'],
      equations: {'Kf': 'Irms/Iavg', 'Irms': 'Kf*Iavg', 'Iavg': 'Irms/Kf'},
    ),
    Formula(
      id: 'hsc2_avg_power_resistive',
      name: 'Average Power (P = VrmsIrms)',
      variables: ['P', 'Vrms', 'Irms'],
      equations: {'P': 'Vrms*Irms', 'Vrms': 'P/Irms', 'Irms': 'P/Vrms'},
    ),

    // ========== CHAPTER 6: GEOMETRICAL OPTICS ==========
    Formula(
      id: 'hsc2_optical_path',
      name: 'Optical Path (L = μl)',
      variables: ['L', 'mu', 'l'],
      equations: {'L': 'mu*l', 'mu': 'L/l', 'l': 'L/mu'},
    ),
    Formula(
      id: 'hsc2_snells_law',
      name: "Snell's Law (sin i / sin r = μ)",
      variables: ['i', 'r', 'mu'],
      equations: {
        'i': 'asin(mu*sin(r))',
        'r': 'asin(sin(i)/mu)',
        'mu': 'sin(i)/sin(r)',
      },
    ),
    Formula(
      id: 'hsc2_critical_angle',
      name: 'Critical Angle (sinθc = 1/μ)',
      variables: ['theta_c', 'mu'],
      equations: {'theta_c': 'asin(1/mu)', 'mu': '1/sin(theta_c)'},
    ),
    Formula(
      id: 'hsc2_refraction_spherical',
      name: 'Refraction Spherical Surface',
      variables: ['mu2', 'v', 'mu1', 'u', 'r'],
      equations: {
        'mu2': 'v*(mu2-mu1)/r-mu1*v/u',
        'v': 'mu2*r*u/(mu2*u-mu1*u+mu1*r)',
        'u': 'mu1*v*r/(mu2*r-mu2*v+mu1*v)',
        'r': '(mu2-mu1)*u*v/(mu2*u-mu1*v)',
      },
    ),
    Formula(
      id: 'hsc2_lens_maker',
      name: "Lens Maker's Formula (Air)",
      variables: ['f', 'mu', 'r1', 'r2'],
      equations: {
        'f': '1/((mu-1)*(1/r1-1/r2))',
        'mu': '1+1/(f*(1/r1-1/r2))',
        'r1': '1/((1/(f*(mu-1)))+1/r2)',
        'r2': '1/((1/r1)-1/(f*(mu-1)))',
      },
    ),
    Formula(
      id: 'hsc2_thin_lens',
      name: 'Thin Lens (1/f = 1/v + 1/u)',
      variables: ['f', 'v', 'u'],
      equations: {'f': '1/(1/v+1/u)', 'v': '1/(1/f-1/u)', 'u': '1/(1/f-1/v)'},
    ),
    Formula(
      id: 'hsc2_power_lens',
      name: 'Power of Lens (P = 1/f)',
      variables: ['P', 'f'],
      equations: {'P': '1/f', 'f': '1/P'},
    ),
    Formula(
      id: 'hsc2_magnification_lens',
      name: 'Magnification (m = v/u)',
      variables: ['m', 'v', 'u'],
      equations: {'m': 'v/u', 'v': 'm*u', 'u': 'v/m'},
    ),
    Formula(
      id: 'hsc2_lens_combination',
      name: 'Lenses in Contact (1/f = 1/f1 + 1/f2)',
      variables: ['f', 'f1', 'f2'],
      equations: {
        'f': '1/(1/f1+1/f2)',
        'f1': '1/(1/f-1/f2)',
        'f2': '1/(1/f-1/f1)',
      },
    ),
    Formula(
      id: 'hsc2_power_combination',
      name: 'Power Combination (P = P1 + P2)',
      variables: ['P', 'P1', 'P2'],
      equations: {'P': 'P1+P2', 'P1': 'P-P2', 'P2': 'P-P1'},
    ),
    Formula(
      id: 'hsc2_simple_microscope_near',
      name: 'Simple Microscope (Near Point)',
      variables: ['m', 'D', 'f'],
      equations: {'m': '1+D/f', 'D': 'f*(m-1)', 'f': 'D/(m-1)'},
    ),
    Formula(
      id: 'hsc2_simple_microscope_inf',
      name: 'Simple Microscope (Infinity)',
      variables: ['m', 'D', 'f'],
      equations: {'m': 'D/f', 'D': 'm*f', 'f': 'D/m'},
    ),
    Formula(
      id: 'hsc2_compound_microscope',
      name: 'Compound Microscope Magnification',
      variables: ['m', 'vo', 'uo', 'D', 'fe'],
      equations: {
        'm': '(vo/uo)*(1+D/fe)',
        'vo': 'm*uo/(1+D/fe)',
        'uo': 'vo*(1+D/fe)/m',
      },
    ),
    Formula(
      id: 'hsc2_telescope_mag_inf',
      name: 'Telescope Magnification (Infinity)',
      variables: ['m', 'fo', 'fe'],
      equations: {'m': 'fo/fe', 'fo': 'm*fe', 'fe': 'fo/m'},
    ),
    Formula(
      id: 'hsc2_telescope_length_inf',
      name: 'Telescope Length (Infinity)',
      variables: ['L', 'fo', 'fe'],
      equations: {'L': 'fo+fe', 'fo': 'L-fe', 'fe': 'L-fo'},
    ),
    Formula(
      id: 'hsc2_telescope_mag_near',
      name: 'Telescope Magnification (Near)',
      variables: ['m', 'fo', 'fe', 'D'],
      equations: {
        'm': '(fo/fe)*(1+fe/D)',
        'fo': 'm*fe/(1+fe/D)',
        'fe': 'm*D/(m+fo/D)',
      },
    ),
    Formula(
      id: 'hsc2_resolving_power_microscope',
      name: 'Resolving Power Microscope',
      variables: ['R', 'mu', 'theta', 'lambda'],
      equations: {
        'R': '2*mu*sin(theta)/lambda',
        'mu': 'R*lambda/(2*sin(theta))',
        'theta': 'asin(R*lambda/(2*mu))',
        'lambda': '2*mu*sin(theta)/R',
      },
    ),
    Formula(
      id: 'hsc2_resolving_power_telescope',
      name: 'Resolving Power Telescope',
      variables: ['R', 'a', 'lambda'],
      equations: {
        'R': 'a/(1.22*lambda)',
        'a': 'R*1.22*lambda',
        'lambda': 'a/(1.22*R)',
      },
    ),
    Formula(
      id: 'hsc2_prism_angle',
      name: 'Prism Angle (A = r1 + r2)',
      variables: ['A', 'r1', 'r2'],
      equations: {'A': 'r1+r2', 'r1': 'A-r2', 'r2': 'A-r1'},
    ),
    Formula(
      id: 'hsc2_prism_deviation',
      name: 'Prism Deviation (δ = i1 + i2 - A)',
      variables: ['delta', 'i1', 'i2', 'A'],
      equations: {
        'delta': 'i1+i2-A',
        'i1': 'delta+A-i2',
        'i2': 'delta+A-i1',
        'A': 'i1+i2-delta',
      },
    ),
    Formula(
      id: 'hsc2_prism_refractive_index',
      name: 'Prism Refractive Index',
      variables: ['mu', 'A', 'delta_m'],
      equations: {
        'mu': 'sin((A+delta_m)/2)/sin(A/2)',
        'A': '2*asin(sin((A+delta_m)/2)/mu)-delta_m',
        'delta_m': '2*asin(mu*sin(A/2))-A',
      },
    ),
    Formula(
      id: 'hsc2_thin_prism_deviation',
      name: 'Thin Prism Deviation (δ = (μ-1)A)',
      variables: ['delta', 'mu', 'A'],
      equations: {'delta': '(mu-1)*A', 'mu': 'delta/A+1', 'A': 'delta/(mu-1)'},
    ),
    Formula(
      id: 'hsc2_angular_dispersion',
      name: 'Angular Dispersion (θ = A(μv - μr))',
      variables: ['theta', 'A', 'muv', 'mur'],
      equations: {
        'theta': 'A*(muv-mur)',
        'A': 'theta/(muv-mur)',
        'muv': 'theta/A+mur',
        'mur': 'muv-theta/A',
      },
    ),
    Formula(
      id: 'hsc2_dispersive_power',
      name: 'Dispersive Power (W = (μv-μr)/(μ-1))',
      variables: ['W', 'muv', 'mur', 'mu'],
      equations: {
        'W': '(muv-mur)/(mu-1)',
        'muv': 'W*(mu-1)+mur',
        'mur': 'muv-W*(mu-1)',
        'mu': '(muv-mur)/W+1',
      },
    ),

    // ========== CHAPTER 7: PHYSICAL OPTICS ==========
    Formula(
      id: 'hsc2_em_wave_speed',
      name: 'EM Wave Speed in Vacuum',
      variables: ['c'],
      equations: {'c': '1/sqrt(8.854e-12*4*3.14159e-7)'},
    ),
    Formula(
      id: 'hsc2_em_wave_medium',
      name: 'EM Wave Speed in Medium',
      variables: ['v', 'epsilon_r', 'mu_r'],
      equations: {
        'v': '3e8/sqrt(epsilon_r*mu_r)',
        'epsilon_r': '(3e8/v)^2/mu_r',
        'mu_r': '(3e8/v)^2/epsilon_r',
      },
    ),
    Formula(
      id: 'hsc2_em_amplitude_ratio',
      name: 'EM Amplitude Ratio (c = E0/B0)',
      variables: ['c', 'E0', 'B0'],
      equations: {'c': 'E0/B0', 'E0': 'c*B0', 'B0': 'E0/c'},
    ),
    Formula(
      id: 'hsc2_phase_path_diff',
      name: 'Phase Difference (δ = 2πσ/λ)',
      variables: ['delta', 'sigma', 'lambda'],
      equations: {
        'delta': '2*3.14159*sigma/lambda',
        'sigma': 'delta*lambda/(2*3.14159)',
        'lambda': '2*3.14159*sigma/delta',
      },
    ),
    Formula(
      id: 'hsc2_constructive_interference',
      name: 'Constructive Interference (σ = nλ)',
      variables: ['sigma', 'n', 'lambda'],
      equations: {
        'sigma': 'n*lambda',
        'n': 'sigma/lambda',
        'lambda': 'sigma/n',
      },
    ),
    Formula(
      id: 'hsc2_destructive_interference',
      name: 'Destructive Interference (σ = (2n+1)λ/2)',
      variables: ['sigma', 'n', 'lambda'],
      equations: {
        'sigma': '(2*n+1)*lambda/2',
        'n': '(2*sigma/lambda-1)/2',
        'lambda': '2*sigma/(2*n+1)',
      },
    ),
    Formula(
      id: 'hsc2_ydse_bright_fringe',
      name: 'YDSE Bright Fringe (xn = nλD/2d)',
      variables: ['xn', 'n', 'lambda', 'D', 'd'],
      equations: {
        'xn': 'n*lambda*D/(2*d)',
        'n': '2*xn*d/(lambda*D)',
        'lambda': '2*xn*d/(n*D)',
        'D': '2*xn*d/(n*lambda)',
        'd': 'n*lambda*D/(2*xn)',
      },
    ),
    Formula(
      id: 'hsc2_ydse_dark_fringe',
      name: 'YDSE Dark Fringe (xn = (2n+1)λD/4d)',
      variables: ['xn', 'n', 'lambda', 'D', 'd'],
      equations: {
        'xn': '(2*n+1)*lambda*D/(4*d)',
        'n': '(4*xn*d/(lambda*D)-1)/2',
        'lambda': '4*xn*d/((2*n+1)*D)',
        'D': '4*xn*d/((2*n+1)*lambda)',
        'd': '(2*n+1)*lambda*D/(4*xn)',
      },
    ),
    Formula(
      id: 'hsc2_ydse_fringe_width',
      name: 'YDSE Fringe Width (β = λD/2d)',
      variables: ['beta', 'lambda', 'D', 'd'],
      equations: {
        'beta': 'lambda*D/(2*d)',
        'lambda': '2*beta*d/D',
        'D': '2*beta*d/lambda',
        'd': 'lambda*D/(2*beta)',
      },
    ),
    Formula(
      id: 'hsc2_single_slit_minima',
      name: 'Single Slit Minima (a sinθ = nλ)',
      variables: ['a', 'theta', 'n', 'lambda'],
      equations: {
        'a': 'n*lambda/sin(theta)',
        'theta': 'asin(n*lambda/a)',
        'n': 'a*sin(theta)/lambda',
        'lambda': 'a*sin(theta)/n',
      },
    ),
    Formula(
      id: 'hsc2_single_slit_maxima',
      name: 'Single Slit Maxima (a sinθ = (2n+1)λ/2)',
      variables: ['a', 'theta', 'n', 'lambda'],
      equations: {
        'a': '(2*n+1)*lambda/(2*sin(theta))',
        'theta': 'asin((2*n+1)*lambda/(2*a))',
        'n': '(2*a*sin(theta)/lambda-1)/2',
        'lambda': '2*a*sin(theta)/(2*n+1)',
      },
    ),
    Formula(
      id: 'hsc2_diffraction_grating',
      name: 'Diffraction Grating (d sinθ = nλ)',
      variables: ['d', 'theta', 'n', 'lambda'],
      equations: {
        'd': 'n*lambda/sin(theta)',
        'theta': 'asin(n*lambda/d)',
        'n': 'd*sin(theta)/lambda',
        'lambda': 'd*sin(theta)/n',
      },
    ),
    Formula(
      id: 'hsc2_grating_constant',
      name: 'Grating Constant (d = 1/N)',
      variables: ['d', 'N'],
      equations: {'d': '1/N', 'N': '1/d'},
    ),
    Formula(
      id: 'hsc2_brewsters_law',
      name: "Brewster's Law (μ = tan ip)",
      variables: ['mu', 'ip'],
      equations: {'mu': 'tan(ip)', 'ip': 'atan(mu)'},
    ),
    Formula(
      id: 'hsc2_malus_law',
      name: "Malus's Law (I = I0 cos²θ)",
      variables: ['I', 'I0', 'theta'],
      equations: {
        'I': 'I0*cos(theta)^2',
        'I0': 'I/cos(theta)^2',
        'theta': 'acos(sqrt(I/I0))',
      },
    ),
    Formula(
      id: 'hsc2_refractive_index_wavelength',
      name: 'Refractive Index and Wavelength',
      variables: ['mu', 'lambda_a', 'lambda_m'],
      equations: {
        'mu': 'lambda_a/lambda_m',
        'lambda_a': 'mu*lambda_m',
        'lambda_m': 'lambda_a/mu',
      },
    ),

    // ========== CHAPTER 8: MODERN PHYSICS ==========
    Formula(
      id: 'hsc2_lorentz_position',
      name: 'Lorentz Transformation Position',
      variables: ['x_prime', 'x', 'v', 't'],
      equations: {
        'x_prime': '(x-v*t)/sqrt(1-v^2/9e16)',
        'x': 'x_prime*sqrt(1-v^2/9e16)+v*t',
        'v': '(x-x_prime*sqrt(1-v^2/9e16))/t',
        't': '(x-x_prime*sqrt(1-v^2/9e16))/v',
      },
    ),
    Formula(
      id: 'hsc2_length_contraction',
      name: 'Length Contraction (L = L0√(1-v²/c²))',
      variables: ['L', 'L0', 'v'],
      equations: {
        'L': 'L0*sqrt(1-v^2/9e16)',
        'L0': 'L/sqrt(1-v^2/9e16)',
        'v': 'sqrt(9e16*(1-(L/L0)^2))',
      },
    ),
    Formula(
      id: 'hsc2_time_dilation',
      name: 'Time Dilation (t = t0/√(1-v²/c²))',
      variables: ['t', 't0', 'v'],
      equations: {
        't': 't0/sqrt(1-v^2/9e16)',
        't0': 't*sqrt(1-v^2/9e16)',
        'v': 'sqrt(9e16*(1-(t0/t)^2))',
      },
    ),
    Formula(
      id: 'hsc2_mass_variation',
      name: 'Mass Variation (m = m0/√(1-v²/c²))',
      variables: ['m', 'm0', 'v'],
      equations: {
        'm': 'm0/sqrt(1-v^2/9e16)',
        'm0': 'm*sqrt(1-v^2/9e16)',
        'v': 'sqrt(9e16*(1-(m0/m)^2))',
      },
    ),
    Formula(
      id: 'hsc2_relativistic_ke',
      name: 'Relativistic KE',
      variables: ['Ek', 'm', 'm0'],
      equations: {'Ek': '(m-m0)*9e16', 'm': 'Ek/9e16+m0', 'm0': 'm-Ek/9e16'},
    ),
    Formula(
      id: 'hsc2_mass_energy',
      name: 'Mass-Energy (E = mc²)',
      variables: ['E', 'm'],
      equations: {'E': 'm*9e16', 'm': 'E/9e16'},
    ),
    Formula(
      id: 'hsc2_energy_momentum',
      name: 'Energy-Momentum (E = √(p²c²+m0²c⁴))',
      variables: ['E', 'p', 'm0'],
      equations: {
        'E': 'sqrt(p^2*9e16+m0^2*8.1e33)',
        'p': 'sqrt(E^2-8.1e33*m0^2)/3e8',
        'm0': 'sqrt(E^2-p^2*9e16)/9e16',
      },
    ),
    Formula(
      id: 'hsc2_photon_energy',
      name: 'Photon Energy (E = hν = hc/λ)',
      variables: ['E', 'nu', 'lambda'],
      equations: {
        'E': '6.626e-34*nu',
        'nu': 'E/6.626e-34',
        'lambda': '6.626e-34*3e8/E',
      },
    ),
    Formula(
      id: 'hsc2_photon_momentum',
      name: 'Photon Momentum (p = h/λ)',
      variables: ['p', 'lambda'],
      equations: {'p': '6.626e-34/lambda', 'lambda': '6.626e-34/p'},
    ),
    Formula(
      id: 'hsc2_xray_cutoff',
      name: 'X-ray Cutoff (λmin = hc/eV)',
      variables: ['lambda_min', 'V'],
      equations: {
        'lambda_min': '6.626e-34*3e8/(1.6e-19*V)',
        'V': '6.626e-34*3e8/(1.6e-19*lambda_min)',
      },
    ),
    Formula(
      id: 'hsc2_max_velocity_electron',
      name: 'Max Velocity Electron (v = √(2eV/m))',
      variables: ['v_max', 'V'],
      equations: {
        'v_max': 'sqrt(2*1.6e-19*V/9.11e-31)',
        'V': '9.11e-31*v_max^2/(2*1.6e-19)',
      },
    ),
    Formula(
      id: 'hsc2_photoelectric_energy',
      name: "Einstein's Photoelectric (hν = W0 + ½mv²)",
      variables: ['h_nu', 'W0', 'v_max'],
      equations: {
        'h_nu': 'W0+0.5*9.11e-31*v_max^2',
        'W0': 'h_nu-0.5*9.11e-31*v_max^2',
        'v_max': 'sqrt(2*(h_nu-W0)/9.11e-31)',
      },
    ),
    Formula(
      id: 'hsc2_work_function',
      name: 'Work Function (W0 = hν0)',
      variables: ['W0', 'nu0', 'lambda0'],
      equations: {
        'W0': '6.626e-34*nu0',
        'nu0': 'W0/6.626e-34',
        'lambda0': '6.626e-34*3e8/W0',
      },
    ),
    Formula(
      id: 'hsc2_stopping_potential',
      name: 'Stopping Potential (eV0 = hν - W0)',
      variables: ['V0', 'nu', 'W0'],
      equations: {
        'V0': '(6.626e-34*nu-W0)/1.6e-19',
        'nu': '(1.6e-19*V0+W0)/6.626e-34',
        'W0': '6.626e-34*nu-1.6e-19*V0',
      },
    ),
    Formula(
      id: 'hsc2_de_broglie',
      name: 'de Broglie Wavelength (λ = h/mv)',
      variables: ['lambda', 'm', 'v'],
      equations: {
        'lambda': '6.626e-34/(m*v)',
        'm': '6.626e-34/(lambda*v)',
        'v': '6.626e-34/(lambda*m)',
      },
    ),
    Formula(
      id: 'hsc2_de_broglie_ke',
      name: 'de Broglie from KE (λ = h/√(2mEk))',
      variables: ['lambda', 'm', 'Ek'],
      equations: {
        'lambda': '6.626e-34/sqrt(2*m*Ek)',
        'm': '6.626e-34^2/(2*Ek*lambda^2)',
        'Ek': '6.626e-34^2/(2*m*lambda^2)',
      },
    ),
    Formula(
      id: 'hsc2_de_broglie_electron',
      name: 'de Broglie Accelerated Electron',
      variables: ['lambda', 'V'],
      equations: {
        'lambda': '6.626e-34/sqrt(2*9.11e-31*1.6e-19*V)',
        'V': '6.626e-34^2/(2*9.11e-31*1.6e-19*lambda^2)',
      },
    ),
    Formula(
      id: 'hsc2_compton_shift',
      name: 'Compton Shift (Δλ = h/m0c (1-cosφ))',
      variables: ['dlambda', 'phi'],
      equations: {
        'dlambda': '6.626e-34/(9.11e-31*3e8)*(1-cos(phi))',
        'phi': 'acos(1-dlambda*9.11e-31*3e8/6.626e-34)',
      },
    ),
    Formula(
      id: 'hsc2_heisenberg_pos',
      name: 'Heisenberg Position-Momentum',
      variables: ['dx', 'dp'],
      equations: {'dx': '1.054e-34/(2*dp)', 'dp': '1.054e-34/(2*dx)'},
    ),
    Formula(
      id: 'hsc2_heisenberg_energy',
      name: 'Heisenberg Energy-Time',
      variables: ['dE', 'dt'],
      equations: {'dE': '1.054e-34/(2*dt)', 'dt': '1.054e-34/(2*dE)'},
    ),
    Formula(
      id: 'hsc2_heisenberg_angular',
      name: 'Heisenberg Angular Momentum',
      variables: ['dL', 'dphi'],
      equations: {'dL': '1.054e-34/(2*dphi)', 'dphi': '1.054e-34/(2*dL)'},
    ),

    // ========== CHAPTER 9: ATOMIC & NUCLEAR PHYSICS ==========
    Formula(
      id: 'hsc2_bohr_angular_momentum',
      name: 'Bohr Angular Momentum',
      variables: ['L', 'n'],
      equations: {'L': 'n*6.626e-34/(2*3.14159)', 'n': 'L*2*3.14159/6.626e-34'},
    ),
    Formula(
      id: 'hsc2_bohr_frequency',
      name: 'Bohr Frequency Condition',
      variables: ['E', 'nu', 'lambda'],
      equations: {
        'E': '6.626e-34*nu',
        'nu': 'E/6.626e-34',
        'lambda': '6.626e-34*3e8/E',
      },
    ),
    Formula(
      id: 'hsc2_bohr_radius_h',
      name: 'Bohr Radius Hydrogen',
      variables: ['r_n', 'n'],
      equations: {'r_n': 'n^2*0.529e-10', 'n': 'sqrt(r_n/0.529e-10)'},
    ),
    Formula(
      id: 'hsc2_bohr_radius_ion',
      name: 'Bohr Radius Hydrogen-like',
      variables: ['r_n', 'n', 'Z'],
      equations: {
        'r_n': 'n^2*0.529e-10/Z',
        'n': 'sqrt(r_n*Z/0.529e-10)',
        'Z': 'n^2*0.529e-10/r_n',
      },
    ),
    Formula(
      id: 'hsc2_bohr_velocity',
      name: 'Bohr Electron Velocity',
      variables: ['v_n', 'n', 'Z'],
      equations: {
        'v_n': '2.18e6*Z/n',
        'n': '2.18e6*Z/v_n',
        'Z': 'v_n*n/2.18e6',
      },
    ),
    Formula(
      id: 'hsc2_bohr_frequency_orbital',
      name: 'Orbital Frequency',
      variables: ['nu_n', 'v_n', 'r_n'],
      equations: {
        'nu_n': 'v_n/(2*3.14159*r_n)',
        'v_n': 'nu_n*2*3.14159*r_n',
        'r_n': 'v_n/(2*3.14159*nu_n)',
      },
    ),
    Formula(
      id: 'hsc2_bohr_energy_h',
      name: 'Bohr Energy Hydrogen (E = -13.6/n² eV)',
      variables: ['E_n', 'n'],
      equations: {'E_n': '-13.6/(n^2)', 'n': 'sqrt(-13.6/E_n)'},
    ),
    Formula(
      id: 'hsc2_bohr_energy_ion',
      name: 'Bohr Energy Hydrogen-like',
      variables: ['E_n', 'n', 'Z'],
      equations: {
        'E_n': '-13.6*Z^2/(n^2)',
        'n': 'sqrt(-13.6*Z^2/E_n)',
        'Z': 'sqrt(-E_n*n^2/13.6)',
      },
    ),
    Formula(
      id: 'hsc2_photon_freq_transition',
      name: 'Photon Frequency Transition',
      variables: ['nu', 'n1', 'n2'],
      equations: {
        'nu': '3.29e15*(1/n1^2-1/n2^2)',
        'n1': 'sqrt(1/(nu/3.29e15+1/n2^2))',
        'n2': 'sqrt(1/(1/n1^2-nu/3.29e15))',
      },
    ),
    Formula(
      id: 'hsc2_nuclear_radius',
      name: 'Nuclear Radius (R = r0 A^(1/3))',
      variables: ['R', 'A'],
      equations: {'R': '1.2e-15*A^(1/3)', 'A': '(R/1.2e-15)^3'},
    ),
    Formula(
      id: 'hsc2_nuclear_density',
      name: 'Nuclear Density',
      variables: ['rho'],
      equations: {'rho': '3*1.67e-27/(4*3.14159*(1.2e-15)^3)'},
    ),
    Formula(
      id: 'hsc2_decay_law',
      name: 'Radioactive Decay (N = N0 e^-λt)',
      variables: ['N', 'N0', 'lambda', 't'],
      equations: {
        'N': 'N0*2.71828^(-lambda*t)',
        'N0': 'N*2.71828^(lambda*t)',
        'lambda': '-ln(N/N0)/t',
        't': '-ln(N/N0)/lambda',
      },
    ),
    Formula(
      id: 'hsc2_mass_decay',
      name: 'Mass Decay (M = M0 e^-λt)',
      variables: ['M', 'M0', 'lambda', 't'],
      equations: {
        'M': 'M0*2.71828^(-lambda*t)',
        'M0': 'M*2.71828^(lambda*t)',
        'lambda': '-ln(M/M0)/t',
        't': '-ln(M/M0)/lambda',
      },
    ),
    Formula(
      id: 'hsc2_activity',
      name: 'Radioactive Activity (A = λN)',
      variables: ['A', 'lambda', 'N'],
      equations: {'A': 'lambda*N', 'lambda': 'A/N', 'N': 'A/lambda'},
    ),
    Formula(
      id: 'hsc2_half_life',
      name: 'Half-Life (T1/2 = 0.693/λ)',
      variables: ['T_half', 'lambda'],
      equations: {'T_half': '0.693/lambda', 'lambda': '0.693/T_half'},
    ),
    Formula(
      id: 'hsc2_mean_life',
      name: 'Mean Life (τ = 1/λ = 1.44 T1/2)',
      variables: ['tau', 'lambda', 'T_half'],
      equations: {'tau': '1/lambda', 'lambda': '1/tau', 'T_half': 'tau/1.44'},
    ),
    Formula(
      id: 'hsc2_remaining_fraction',
      name: 'Remaining Fraction (N/N0 = (1/2)^n)',
      variables: ['N_ratio', 'n'],
      equations: {'N_ratio': '(0.5)^n', 'n': 'ln(N_ratio)/ln(0.5)'},
    ),
    Formula(
      id: 'hsc2_mass_defect',
      name: 'Mass Defect',
      variables: ['dm', 'Z', 'mp', 'A', 'mn', 'M_nuc'],
      equations: {'dm': 'Z*mp+(A-Z)*mn-M_nuc', 'M_nuc': 'Z*mp+(A-Z)*mn-dm'},
    ),
    Formula(
      id: 'hsc2_binding_energy',
      name: 'Binding Energy (BE = Δm c²)',
      variables: ['BE', 'dm'],
      equations: {'BE': 'dm*931.5', 'dm': 'BE/931.5'},
    ),
    Formula(
      id: 'hsc2_binding_energy_per_nucleon',
      name: 'Binding Energy per Nucleon',
      variables: ['Eb', 'BE', 'A'],
      equations: {'Eb': 'BE/A', 'BE': 'Eb*A', 'A': 'BE/Eb'},
    ),
    Formula(
      id: 'hsc2_q_value',
      name: 'Q-Value of Nuclear Reaction',
      variables: ['Q', 'm_reactants', 'm_products'],
      equations: {
        'Q': '(m_reactants-m_products)*931.5',
        'm_reactants': 'Q/931.5+m_products',
        'm_products': 'm_reactants-Q/931.5',
      },
    ),

    // ========== CHAPTER 10: SEMICONDUCTORS ==========
    Formula(
      id: 'hsc2_mass_action',
      name: 'Law of Mass Action (n·p = ni²)',
      variables: ['n', 'p', 'ni'],
      equations: {'n': 'ni^2/p', 'p': 'ni^2/n', 'ni': 'sqrt(n*p)'},
    ),
    Formula(
      id: 'hsc2_diode_dynamic_resistance',
      name: 'Diode Dynamic Resistance (R = ΔV/ΔI)',
      variables: ['R', 'dV', 'dI'],
      equations: {'R': 'dV/dI', 'dV': 'R*dI', 'dI': 'dV/R'},
    ),
    Formula(
      id: 'hsc2_semi_photon_energy',
      name: 'Photon Energy (E = hν)',
      variables: ['E', 'nu', 'lambda'],
      equations: {
        'E': '6.626e-34*nu',
        'nu': 'E/6.626e-34',
        'lambda': '6.626e-34*3e8/E',
      },
    ),
    Formula(
      id: 'hsc2_depletion_field',
      name: 'Depletion Layer Field (E = V/d)',
      variables: ['E', 'V', 'd'],
      equations: {'E': 'V/d', 'V': 'E*d', 'd': 'V/E'},
    ),
    Formula(
      id: 'hsc2_full_wave_dc',
      name: 'Full-Wave DC Current (Idc = 2Im/π)',
      variables: ['Idc', 'Im'],
      equations: {'Idc': '2*Im/3.14159', 'Im': 'Idc*3.14159/2'},
    ),
    Formula(
      id: 'hsc2_transistor_current',
      name: 'Transistor Current (IE = IB + IC)',
      variables: ['IE', 'IB', 'IC'],
      equations: {'IE': 'IB+IC', 'IB': 'IE-IC', 'IC': 'IE-IB'},
    ),
    Formula(
      id: 'hsc2_transistor_delta_current',
      name: 'Transistor Delta Current',
      variables: ['dIE', 'dIB', 'dIC'],
      equations: {'dIE': 'dIB+dIC', 'dIB': 'dIE-dIC', 'dIC': 'dIE-dIB'},
    ),
    Formula(
      id: 'hsc2_ac_input_resistance',
      name: 'AC Input Resistance (Rin)',
      variables: ['Rin', 'dVBE', 'dIB'],
      equations: {'Rin': 'dVBE/dIB', 'dVBE': 'Rin*dIB', 'dIB': 'dVBE/Rin'},
    ),
    Formula(
      id: 'hsc2_ac_output_resistance',
      name: 'AC Output Resistance (Rout)',
      variables: ['Rout', 'dVCE', 'dIC'],
      equations: {'Rout': 'dVCE/dIC', 'dVCE': 'Rout*dIC', 'dIC': 'dVCE/Rout'},
    ),
    Formula(
      id: 'hsc2_beta_gain',
      name: 'Beta Current Gain (β = ΔIC/ΔIB)',
      variables: ['beta', 'dIC', 'dIB'],
      equations: {'beta': 'dIC/dIB', 'dIC': 'beta*dIB', 'dIB': 'dIC/beta'},
    ),
    Formula(
      id: 'hsc2_alpha_gain',
      name: 'Alpha Current Gain (α = ΔIC/ΔIE)',
      variables: ['alpha', 'dIC', 'dIE'],
      equations: {'alpha': 'dIC/dIE', 'dIC': 'alpha*dIE', 'dIE': 'dIC/alpha'},
    ),
    Formula(
      id: 'hsc2_alpha_beta_relation',
      name: 'Alpha-Beta Relation (β = α/(1-α))',
      variables: ['beta', 'alpha'],
      equations: {'beta': 'alpha/(1-alpha)', 'alpha': 'beta/(1+beta)'},
    ),
    Formula(
      id: 'hsc2_voltage_gain',
      name: 'Voltage Gain (Av = β RL/Ri)',
      variables: ['Av', 'beta', 'RL', 'Ri'],
      equations: {
        'Av': 'beta*RL/Ri',
        'beta': 'Av*Ri/RL',
        'RL': 'Av*Ri/beta',
        'Ri': 'beta*RL/Av',
      },
    ),
    Formula(
      id: 'hsc2_power_gain',
      name: 'Power Gain (Ap = β Av)',
      variables: ['Ap', 'beta', 'Av'],
      equations: {'Ap': 'beta*Av', 'beta': 'Ap/Av', 'Av': 'Ap/beta'},
    ),
    Formula(
      id: 'hsc2_transistor_switch',
      name: 'Transistor Switch (Vo = VS - ICRL)',
      variables: ['Vo', 'VS', 'IC', 'RL'],
      equations: {
        'Vo': 'VS-IC*RL',
        'VS': 'Vo+IC*RL',
        'IC': '(VS-Vo)/RL',
        'RL': '(VS-Vo)/IC',
      },
    ),
    Formula(
      id: 'hsc2_de_morgan1',
      name: "De Morgan's First Theorem",
      variables: ['Y', 'A', 'B'],
      equations: {'Y': '1-A*B', 'A': '(1-Y)/B', 'B': '(1-Y)/A'},
    ),
    Formula(
      id: 'hsc2_de_morgan2',
      name: "De Morgan's Second Theorem",
      variables: ['Y', 'A', 'B'],
      equations: {'Y': '1-(A+B)', 'A': '1-Y-B', 'B': '1-Y-A'},
    ),
    Formula(
      id: 'hsc2_xor_gate',
      name: 'XOR Gate Boolean Expression',
      variables: ['X', 'A', 'B'],
      equations: {'X': '(1-A)*B+A*(1-B)', 'A': 'X', 'B': 'X'},
    ),
    Formula(
      id: 'hsc2_xnor_gate',
      name: 'X-NOR Gate Boolean Expression',
      variables: ['X', 'A', 'B'],
      equations: {'X': 'A*B+(1-A)*(1-B)', 'A': 'X', 'B': 'X'},
    ),

    // ========== CHAPTER 11: ASTRONOMY ==========
    Formula(
      id: 'hsc2_hubble_law',
      name: "Hubble's Law (v = Hd)",
      variables: ['v', 'H', 'd'],
      equations: {'v': 'H*d', 'H': 'v/d', 'd': 'v/H'},
    ),
    Formula(
      id: 'hsc2_magnitude_diff',
      name: 'Magnitude Difference (m2-m1 = 5 log(d2/d1))',
      variables: ['m2', 'm1', 'd2', 'd1'],
      equations: {
        'm2': 'm1+5*log(d2/d1)',
        'm1': 'm2-5*log(d2/d1)',
        'd2': 'd1*10^((m2-m1)/5)',
        'd1': 'd2*10^((m1-m2)/5)',
      },
    ),
    Formula(
      id: 'hsc2_solar_luminosity',
      name: 'Solar Luminosity (Ls = 4πR²s)',
      variables: ['Ls', 'R', 's'],
      equations: {
        'Ls': '4*3.14159*R^2*s',
        'R': 'sqrt(Ls/(4*3.14159*s))',
        's': 'Ls/(4*3.14159*R^2)',
      },
    ),
    Formula(
      id: 'hsc2_solar_mass_energy',
      name: 'Solar Mass-Energy (ΔE = Δmc²)',
      variables: ['dE', 'dm'],
      equations: {'dE': 'dm*9e16', 'dm': 'dE/9e16'},
    ),
    Formula(
      id: 'hsc2_schwarzschild_radius',
      name: 'Schwarzschild Radius (Rs = 2GM/c²)',
      variables: ['Rs', 'M'],
      equations: {'Rs': '2*6.674e-11*M/9e16', 'M': 'Rs*9e16/(2*6.674e-11)'},
    ),
    Formula(
      id: 'hsc2_critical_density',
      name: 'Critical Density (ρc = 3H²/8πG)',
      variables: ['rho_c', 'H'],
      equations: {
        'rho_c': '3*H^2/(8*3.14159*6.674e-11)',
        'H': 'sqrt(rho_c*8*3.14159*6.674e-11/3)',
      },
    ),
    Formula(
      id: 'hsc2_density_parameter',
      name: 'Density Parameter (Ω = ρ/ρc)',
      variables: ['Omega', 'rho', 'rho_c'],
      equations: {
        'Omega': 'rho/rho_c',
        'rho': 'Omega*rho_c',
        'rho_c': 'rho/Omega',
      },
    ),
    Formula(
      id: 'hsc2_doppler_shift',
      name: 'Doppler Shift (v/c = Δλ/λ0)',
      variables: ['v', 'dlambda', 'lambda0'],
      equations: {
        'v': '3e8*dlambda/lambda0',
        'dlambda': 'v*lambda0/3e8',
        'lambda0': '3e8*dlambda/v',
      },
    ),
    Formula(
      id: 'hsc2_orbital_velocity',
      name: 'Orbital Velocity (v = √(GM/r))',
      variables: ['v', 'M', 'r'],
      equations: {
        'v': 'sqrt(6.674e-11*M/r)',
        'M': 'v^2*r/6.674e-11',
        'r': '6.674e-11*M/v^2',
      },
    ),
    Formula(
      id: 'hsc2_orbital_period',
      name: 'Orbital Period (T = 2π√(r³/GM))',
      variables: ['T', 'r', 'M'],
      equations: {
        'T': '2*3.14159*sqrt(r^3/(6.674e-11*M))',
        'r': '(T^2*6.674e-11*M/(4*3.14159^2))^(1/3)',
        'M': '4*3.14159^2*r^3/(6.674e-11*T^2)',
      },
    ),
    Formula(
      id: 'hsc2_escape_velocity_earth',
      name: 'Escape Velocity (ve = √(2GM/R))',
      variables: ['ve', 'M', 'R'],
      equations: {
        've': 'sqrt(2*6.674e-11*M/R)',
        'M': 've^2*R/(2*6.674e-11)',
        'R': '2*6.674e-11*M/ve^2',
      },
    ),
    Formula(
      id: 'hsc2_chandrasekhar',
      name: 'Chandrasekhar Limit (Mlim = 1.4 M0)',
      variables: ['M_lim', 'M0'],
      equations: {'M_lim': '1.4*M0', 'M0': 'M_lim/1.4'},
    ),
    Formula(
      id: 'hsc2_black_hole_density',
      name: 'Black Hole Density (ρ = M/V)',
      variables: ['rho', 'M', 'Rs'],
      equations: {
        'rho': 'M/(4*3.14159*Rs^3/3)',
        'M': 'rho*4*3.14159*Rs^3/3',
        'Rs': '(3*M/(4*3.14159*rho))^(1/3)',
      },
    ),
  ];
}
