import '../formula.dart';

class HscPhysics1Database {
  static final List<Formula> hscPhysics1Formulas = [
    // ========== CHAPTER 1: DIMENSIONAL ANALYSIS & BASICS ==========
    Formula(
      id: 'hsc_pendulum_period',
      name: 'Simple Pendulum Period (T = 2π√(l/g))',
      variables: ['T', 'l', 'g'],
      equations: {
        'T': '2*3.14159*sqrt(l/g)',
        'l': 'g*(T/(2*3.14159))^2',
        'g': 'l/(T/(2*3.14159))^2',
      },
    ),
    Formula(
      id: 'hsc_stokes_law',
      name: "Stokes' Law (F = 6πηrv)",
      variables: ['F', 'eta', 'r', 'v'],
      equations: {
        'F': '6*3.14159*eta*r*v',
        'eta': 'F/(6*3.14159*r*v)',
        'r': 'F/(6*3.14159*eta*v)',
        'v': 'F/(6*3.14159*eta*r)',
      },
    ),
    Formula(
      id: 'hsc_transverse_freq',
      name: 'Transverse Frequency of Stretched String',
      variables: ['n', 'l', 'T', 'm'],
      equations: {
        'n': '(1/(2*l))*sqrt(T/m)',
        'l': 'sqrt(T/m)/(2*n)',
        'T': 'm*(2*l*n)^2',
        'm': 'T/((2*l*n)^2)',
      },
    ),
    Formula(
      id: 'hsc_plane_angle',
      name: 'Plane Angle (θ = s/r)',
      variables: ['theta', 's', 'r'],
      equations: {'theta': 's/r', 's': 'theta*r', 'r': 's/theta'},
    ),
    Formula(
      id: 'hsc_electric_field_intensity',
      name: 'Electric Field Intensity (E = F/q)',
      variables: ['E', 'F', 'q'],
      equations: {'E': 'F/q', 'F': 'E*q', 'q': 'F/E'},
    ),
    Formula(
      id: 'hsc_mass_energy',
      name: "Einstein Mass-Energy (E = mc²)",
      variables: ['E', 'm'],
      equations: {'E': 'm*(3e8)^2', 'm': 'E/((3e8)^2)'},
    ),

    // ========== CHAPTER 2: VECTORS ==========
    Formula(
      id: 'hsc_torque_mag',
      name: 'Torque Magnitude (τ = rFsinθ)',
      variables: ['tau', 'r', 'F', 'theta'],
      equations: {
        'tau': 'r*F*sin(theta)',
        'r': 'tau/(F*sin(theta))',
        'F': 'tau/(r*sin(theta))',
        'theta': 'asin(tau/(r*F))',
      },
    ),
    Formula(
      id: 'hsc_linear_angular_v',
      name: 'Linear Velocity from Angular (v = ωr)',
      variables: ['v', 'omega', 'r'],
      equations: {'v': 'omega*r', 'omega': 'v/r', 'r': 'v/omega'},
    ),
    Formula(
      id: 'hsc_angular_momentum_mag',
      name: 'Angular Momentum Magnitude (L = rPsinθ)',
      variables: ['L', 'r', 'P', 'theta'],
      equations: {
        'L': 'r*P*sin(theta)',
        'r': 'L/(P*sin(theta))',
        'P': 'L/(r*sin(theta))',
        'theta': 'asin(L/(r*P))',
      },
    ),
    Formula(
      id: 'hsc_position_vec_mag',
      name: 'Position Vector Magnitude (r = √(x²+y²+z²))',
      variables: ['r', 'x', 'y', 'z'],
      equations: {
        'r': 'sqrt(x^2+y^2+z^2)',
        'x': 'sqrt(r^2-y^2-z^2)',
        'y': 'sqrt(r^2-x^2-z^2)',
        'z': 'sqrt(r^2-x^2-y^2)',
      },
    ),
    Formula(
      id: 'hsc_displacement_mag_3d',
      name: 'Displacement Magnitude in 3D',
      variables: ['d', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2'],
      equations: {
        'd': 'sqrt((x2-x1)^2+(y2-y1)^2+(z2-z1)^2)',
        'x1': 'x2 - sqrt(d^2-(y2-y1)^2-(z2-z1)^2)',
        'x2': 'x1 + sqrt(d^2-(y2-y1)^2-(z2-z1)^2)',
      },
    ),
    Formula(
      id: 'hsc_parallelogram_resultant',
      name: 'Parallelogram Resultant (R = √(P²+Q²+2PQcosα))',
      variables: ['R', 'P', 'Q', 'alpha'],
      equations: {
        'R': 'sqrt(P^2+Q^2+2*P*Q*cos(alpha))',
        'P': 'sqrt(R^2-Q^2*sin(alpha)^2)-Q*cos(alpha)',
        'Q': 'sqrt(R^2-P^2*sin(alpha)^2)-P*cos(alpha)',
        'alpha': 'acos((R^2-P^2-Q^2)/(2*P*Q))',
      },
    ),
    Formula(
      id: 'hsc_resultant_direction',
      name: 'Direction of Resultant (θ = tan⁻¹(Qsinα/(P+Qcosα)))',
      variables: ['theta', 'P', 'Q', 'alpha'],
      equations: {
        'theta': 'atan((Q*sin(alpha))/(P+Q*cos(alpha)))',
        'alpha': 'asin((sin(theta)*P)/(Q*(cos(theta)-sin(theta))))',
      },
    ),
    Formula(
      id: 'hsc_max_resultant',
      name: 'Maximum Resultant (R = P + Q)',
      variables: ['R', 'P', 'Q'],
      equations: {'R': 'P+Q', 'P': 'R-Q', 'Q': 'R-P'},
    ),
    Formula(
      id: 'hsc_min_resultant',
      name: 'Minimum Resultant (R = |P - Q|)',
      variables: ['R', 'P', 'Q'],
      equations: {'R': 'abs(P-Q)', 'P': 'R+Q', 'Q': 'R+P'},
    ),
    Formula(
      id: 'hsc_perpendicular_resultant',
      name: 'Perpendicular Vectors Resultant (R = √(P²+Q²))',
      variables: ['R', 'P', 'Q'],
      equations: {
        'R': 'sqrt(P^2+Q^2)',
        'P': 'sqrt(R^2-Q^2)',
        'Q': 'sqrt(R^2-P^2)',
      },
    ),
    Formula(
      id: 'hsc_river_crossing_time',
      name: 'River Crossing Time (t = d/v)',
      variables: ['t', 'd', 'v'],
      equations: {'t': 'd/v', 'd': 't*v', 'v': 'd/t'},
    ),
    Formula(
      id: 'hsc_boat_resultant_v',
      name: 'Resultant Boat Velocity (w = √(u²+v²))',
      variables: ['w', 'u', 'v'],
      equations: {
        'w': 'sqrt(u^2+v^2)',
        'u': 'sqrt(w^2-v^2)',
        'v': 'sqrt(w^2-u^2)',
      },
    ),
    Formula(
      id: 'hsc_steering_angle',
      name: 'Steering Angle (sinθ = u/v)',
      variables: ['theta', 'u', 'v'],
      equations: {
        'theta': 'asin(u/v)',
        'u': 'v*sin(theta)',
        'v': 'u/sin(theta)',
      },
    ),
    Formula(
      id: 'hsc_min_dist_cross_time',
      name: 'Min Distance Crossing Time (t = d/√(v²-u²))',
      variables: ['t', 'd', 'v', 'u'],
      equations: {
        't': 'd/sqrt(v^2-u^2)',
        'd': 't*sqrt(v^2-u^2)',
        'v': 'sqrt((d/t)^2+u^2)',
        'u': 'sqrt(v^2-(d/t)^2)',
      },
    ),
    Formula(
      id: 'hsc_min_time_cross',
      name: 'Minimum Time to Cross (t = d/v)',
      variables: ['t', 'd', 'v'],
      equations: {'t': 'd/v', 'd': 't*v', 'v': 'd/t'},
    ),
    Formula(
      id: 'hsc_rain_relative_v',
      name: 'Relative Velocity of Rain (perpendicular)',
      variables: ['vrm', 'vr', 'vm'],
      equations: {
        'vrm': 'sqrt(vr^2+vm^2)',
        'vr': 'sqrt(vrm^2-vm^2)',
        'vm': 'sqrt(vrm^2-vr^2)',
      },
    ),
    Formula(
      id: 'hsc_umbrella_angle',
      name: 'Umbrella Angle (tanθ = vm/vr)',
      variables: ['theta', 'vm', 'vr'],
      equations: {
        'theta': 'atan(vm/vr)',
        'vm': 'vr*tan(theta)',
        'vr': 'vm/tan(theta)',
      },
    ),
    Formula(
      id: 'hsc_vector_diff_mag',
      name: 'Magnitude of Vector Difference (|A-B|)',
      variables: ['R', 'A', 'B', 'alpha'],
      equations: {
        'R': 'sqrt(A^2+B^2-2*A*B*cos(alpha))',
        'alpha': 'acos((A^2+B^2-R^2)/(2*A*B))',
      },
    ),
    Formula(
      id: 'hsc_vector_diff_direction',
      name: 'Direction of Vector Difference',
      variables: ['phi', 'A', 'B', 'alpha'],
      equations: {
        'phi': 'atan((B*sin(alpha))/(A-B*cos(alpha)))',
        'alpha': 'asin((sin(phi)*A)/(B*(cos(phi)+sin(phi))))',
      },
    ),
    Formula(
      id: 'hsc_components_arbitrary',
      name: 'Components along Arbitrary Directions (a, b)',
      variables: ['a', 'b', 'R', 'alpha', 'beta'],
      equations: {
        'a': '(R*sin(beta))/(sin(alpha+beta))',
        'b': '(R*sin(alpha))/(sin(alpha+beta))',
        'R': '(a*sin(alpha+beta))/(sin(beta))',
        'alpha': 'atan((R*sin(beta)-a*cos(beta))/(a*sin(beta)))',
        'beta': 'atan((R*sin(alpha)-b*cos(alpha))/(b*sin(alpha)))',
      },
    ),
    Formula(
      id: 'hsc_rectangular_components',
      name: 'Rectangular Components (a = Rcosα, b = Rsinα)',
      variables: ['a', 'b', 'R', 'alpha'],
      equations: {
        'a': 'R*cos(alpha)',
        'b': 'R*sin(alpha)',
        'R': 'sqrt(a^2+b^2)',
        'alpha': 'atan(b/a)',
      },
    ),
    Formula(
      id: 'hsc_direction_cosines',
      name: 'Direction Cosines (l = Ax/A)',
      variables: ['l', 'Ax', 'A'],
      equations: {'l': 'Ax/A', 'Ax': 'l*A', 'A': 'Ax/l'},
    ),
    Formula(
      id: 'hsc_sum_sq_dir_cosines',
      name: 'Sum of Squares of Direction Cosines (l²+m²+n²=1)',
      variables: ['l', 'm', 'n'],
      equations: {
        'l': 'sqrt(1-m^2-n^2)',
        'm': 'sqrt(1-l^2-n^2)',
        'n': 'sqrt(1-l^2-m^2)',
      },
    ),
    Formula(
      id: 'hsc_vector_sum_mag_3d',
      name: 'Magnitude of 3D Vector Sum',
      variables: ['R', 'Ax', 'Ay', 'Az', 'Bx', 'By', 'Bz'],
      equations: {'R': 'sqrt((Ax+Bx)^2+(Ay+By)^2+(Az+Bz)^2)'},
    ),
    Formula(
      id: 'hsc_vector_diff_mag_3d',
      name: 'Magnitude of 3D Vector Difference',
      variables: ['R', 'Ax', 'Ay', 'Az', 'Bx', 'By', 'Bz'],
      equations: {'R': 'sqrt((Ax-Bx)^2+(Ay-By)^2+(Az-Bz)^2)'},
    ),

    // ========== CHAPTER 3: DYNAMICS ==========
    Formula(
      id: 'hsc_pos_2d',
      name: 'Position in 2D (r = √(x²+y²))',
      variables: ['r', 'x', 'y'],
      equations: {
        'r': 'sqrt(x^2+y^2)',
        'x': 'sqrt(r^2-y^2)',
        'y': 'sqrt(r^2-x^2)',
      },
    ),
    Formula(
      id: 'hsc_speed',
      name: 'Speed (v = s/t)',
      variables: ['v', 's', 't'],
      equations: {'v': 's/t', 's': 'v*t', 't': 's/v'},
    ),
    Formula(
      id: 'hsc_avg_velocity',
      name: 'Average Velocity (v = Δx/Δt)',
      variables: ['v', 'dx', 'dt'],
      equations: {'v': 'dx/dt', 'dx': 'v*dt', 'dt': 'dx/v'},
    ),
    Formula(
      id: 'hsc_mean_velocity',
      name: 'Mean Velocity (v = (v0+v)/2)',
      variables: ['vmean', 'v0', 'v'],
      equations: {'vmean': '(v0+v)/2', 'v0': '2*vmean-v', 'v': '2*vmean-v0'},
    ),
    Formula(
      id: 'hsc_relative_velocity_same',
      name: 'Relative Velocity (Same Direction)',
      variables: ['vab', 'va', 'vb'],
      equations: {'vab': 'va-vb', 'va': 'vab+vb', 'vb': 'va-vab'},
    ),
    Formula(
      id: 'hsc_relative_velocity_opp',
      name: 'Relative Velocity (Opposite Direction)',
      variables: ['vab', 'va', 'vb'],
      equations: {'vab': 'va+vb', 'va': 'vab-vb', 'vb': 'vab-va'},
    ),
    Formula(
      id: 'hsc_relative_velocity_at_angle',
      name: 'Relative Velocity at Angle',
      variables: ['v', 'v1', 'v2', 'alpha'],
      equations: {
        'v': 'sqrt(v1^2+v2^2-2*v1*v2*cos(alpha))',
        'alpha': 'acos((v1^2+v2^2-v^2)/(2*v1*v2))',
      },
    ),
    Formula(
      id: 'hsc_velocity_uniform_accel',
      name: 'Velocity under Uniform Acceleration (v = v0 + at)',
      variables: ['v', 'v0', 'a', 't'],
      equations: {
        'v': 'v0+a*t',
        'v0': 'v-a*t',
        'a': '(v-v0)/t',
        't': '(v-v0)/a',
      },
    ),
    Formula(
      id: 'hsc_velocity_deceleration',
      name: 'Velocity under Uniform Deceleration (v = v0 - at)',
      variables: ['v', 'v0', 'a', 't'],
      equations: {
        'v': 'v0-a*t',
        'v0': 'v+a*t',
        'a': '(v0-v)/t',
        't': '(v0-v)/a',
      },
    ),
    Formula(
      id: 'hsc_displacement_uniform_accel',
      name: 'Displacement (s = v0t + ½at²)',
      variables: ['s', 'v0', 'a', 't'],
      equations: {
        's': 'v0*t+0.5*a*t^2',
        'v0': '(s-0.5*a*t^2)/t',
        'a': '2*(s-v0*t)/(t^2)',
        't': '(-v0+sqrt(v0^2+2*a*s))/a',
      },
    ),
    Formula(
      id: 'hsc_displacement_from_rest',
      name: 'Displacement from Rest (s = ½at²)',
      variables: ['s', 'a', 't'],
      equations: {'s': '0.5*a*t^2', 'a': '2*s/(t^2)', 't': 'sqrt(2*s/a)'},
    ),
    Formula(
      id: 'hsc_displacement_deceleration',
      name: 'Displacement under Deceleration (s = v0t - ½at²)',
      variables: ['s', 'v0', 'a', 't'],
      equations: {
        's': 'v0*t-0.5*a*t^2',
        'v0': '(s+0.5*a*t^2)/t',
        'a': '2*(v0*t-s)/(t^2)',
        't': '(v0-sqrt(v0^2-2*a*s))/a',
      },
    ),
    Formula(
      id: 'hsc_velocity_displacement',
      name: 'Velocity-Displacement (v² = v0² + 2as)',
      variables: ['v', 'v0', 'a', 's'],
      equations: {
        'v': 'sqrt(v0^2+2*a*s)',
        'v0': 'sqrt(v^2-2*a*s)',
        'a': '(v^2-v0^2)/(2*s)',
        's': '(v^2-v0^2)/(2*a)',
      },
    ),
    Formula(
      id: 'hsc_velocity_from_rest_displacement',
      name: 'Velocity from Rest (v² = 2as)',
      variables: ['v', 'a', 's'],
      equations: {'v': 'sqrt(2*a*s)', 'a': 'v^2/(2*s)', 's': 'v^2/(2*a)'},
    ),
    Formula(
      id: 'hsc_braking_distance',
      name: 'Braking Distance (s = v0²/2a)',
      variables: ['s', 'v0', 'a'],
      equations: {'s': 'v0^2/(2*a)', 'v0': 'sqrt(2*a*s)', 'a': 'v0^2/(2*s)'},
    ),
    Formula(
      id: 'hsc_displacement_tth_second',
      name: 'Displacement in t-th Second (st = v0 + ½a(2t-1))',
      variables: ['st', 'v0', 'a', 't'],
      equations: {
        'st': 'v0+0.5*a*(2*t-1)',
        'v0': 'st-0.5*a*(2*t-1)',
        'a': '(st-v0)/(0.5*(2*t-1))',
        't': '((st-v0)/(0.5*a)+1)/2',
      },
    ),
    Formula(
      id: 'hsc_position_uniform_accel',
      name: 'Position with Uniform Acceleration (x = x0 + v0t + ½at²)',
      variables: ['x', 'x0', 'v0', 'a', 't'],
      equations: {
        'x': 'x0+v0*t+0.5*a*t^2',
        'x0': 'x-v0*t-0.5*a*t^2',
        'v0': '(x-x0-0.5*a*t^2)/t',
        'a': '2*(x-x0-v0*t)/(t^2)',
      },
    ),
    Formula(
      id: 'hsc_position_uniform_velocity',
      name: 'Position with Uniform Velocity (x = x0 + v0t)',
      variables: ['x', 'x0', 'v0', 't'],
      equations: {
        'x': 'x0+v0*t',
        'x0': 'x-v0*t',
        'v0': '(x-x0)/t',
        't': '(x-x0)/v0',
      },
    ),
    Formula(
      id: 'hsc_distance_uniform_velocity',
      name: 'Distance with Uniform Velocity (s = vt)',
      variables: ['s', 'v', 't'],
      equations: {'s': 'v*t', 'v': 's/t', 't': 's/v'},
    ),

    // ========== CHAPTER 4: NEWTONIAN MECHANICS ==========
    Formula(
      id: 'hsc_force_newton2',
      name: "Newton's 2nd Law (F = ma)",
      variables: ['F', 'm', 'a'],
      equations: {'F': 'm*a', 'm': 'F/a', 'a': 'F/m'},
    ),
    Formula(
      id: 'hsc_momentum',
      name: 'Linear Momentum (P = mv)',
      variables: ['P', 'm', 'v'],
      equations: {'P': 'm*v', 'm': 'P/v', 'v': 'P/m'},
    ),
    Formula(
      id: 'hsc_impulse',
      name: 'Impulse (J = F·t = mv - mv0)',
      variables: ['J', 'F', 't', 'm', 'v', 'v0'],
      equations: {
        'J': 'F*t',
        'F': 'J/t',
        't': 'J/F',
        'v': '(J+m*v0)/m',
        'v0': '(m*v-J)/m',
        'm': 'J/(v-v0)',
      },
    ),
    Formula(
      id: 'hsc_recoil_velocity',
      name: 'Recoil Velocity of Gun (V = -mv/M)',
      variables: ['V', 'M', 'm', 'v'],
      equations: {'V': '-m*v/M', 'M': '-m*v/V', 'm': '-M*V/v', 'v': '-M*V/m'},
    ),
    Formula(
      id: 'hsc_rocket_thrust',
      name: 'Rocket Thrust (F = vr · dm/dt)',
      variables: ['F', 'vr', 'dmdt'],
      equations: {'F': 'vr*dmdt', 'vr': 'F/dmdt', 'dmdt': 'F/vr'},
    ),
    Formula(
      id: 'hsc_rocket_accel',
      name: 'Rocket Acceleration (no gravity)',
      variables: ['a', 'M', 'vr', 'dmdt'],
      equations: {
        'a': '(1/M)*dmdt*vr',
        'M': 'dmdt*vr/a',
        'vr': 'a*M/dmdt',
        'dmdt': 'a*M/vr',
      },
    ),
    Formula(
      id: 'hsc_rocket_accel_gravity',
      name: 'Rocket Acceleration (with gravity)',
      variables: ['a', 'M', 'vr', 'dmdt', 'g'],
      equations: {
        'a': '(1/M)*dmdt*vr-g',
        'M': 'dmdt*vr/(a+g)',
        'vr': '(a+g)*M/dmdt',
        'dmdt': '(a+g)*M/vr',
        'g': '(1/M)*dmdt*vr-a',
      },
    ),
    Formula(
      id: 'hsc_apparent_weight_up',
      name: 'Apparent Weight (Lift Going Up)',
      variables: ['R', 'm', 'g', 'a'],
      equations: {'R': 'm*(g+a)', 'm': 'R/(g+a)', 'g': 'R/m-a', 'a': 'R/m-g'},
    ),
    Formula(
      id: 'hsc_apparent_weight_down',
      name: 'Apparent Weight (Lift Going Down)',
      variables: ['R', 'm', 'g', 'a'],
      equations: {'R': 'm*(g-a)', 'm': 'R/(g-a)', 'g': 'R/m+a', 'a': 'g-R/m'},
    ),
    Formula(
      id: 'hsc_super_weightless',
      name: 'Super-Weightlessness (R = m(a-g))',
      variables: ['R', 'm', 'a', 'g'],
      equations: {'R': 'm*(a-g)', 'm': 'R/(a-g)', 'a': 'R/m+g', 'g': 'a-R/m'},
    ),
    Formula(
      id: 'hsc_heisenberg',
      name: "Heisenberg Uncertainty (Δx ≈ h/(mΔvx))",
      variables: ['dx', 'h', 'm', 'dvx'],
      equations: {
        'dx': 'h/(m*dvx)',
        'h': 'dx*m*dvx',
        'm': 'h/(dx*dvx)',
        'dvx': 'h/(m*dx)',
      },
    ),

    // ========== CHAPTER 5: WORK, ENERGY, POWER ==========
    Formula(
      id: 'hsc_work_constant',
      name: 'Work (W = Fs)',
      variables: ['W', 'F', 's'],
      equations: {'W': 'F*s', 'F': 'W/s', 's': 'W/F'},
    ),
    Formula(
      id: 'hsc_work_angle',
      name: 'Work at Angle (W = Fs·cosθ)',
      variables: ['W', 'F', 's', 'theta'],
      equations: {
        'W': 'F*s*cos(theta)',
        'F': 'W/(s*cos(theta))',
        's': 'W/(F*cos(theta))',
        'theta': 'acos(W/(F*s))',
      },
    ),
    Formula(
      id: 'hsc_work_energy_theorem',
      name: 'Work-Energy Theorem (W = ΔKE)',
      variables: ['W', 'm', 'v', 'v0'],
      equations: {
        'W': '0.5*m*v^2-0.5*m*v0^2',
        'm': 'W/(0.5*(v^2-v0^2))',
        'v': 'sqrt((2*W)/m+v0^2)',
        'v0': 'sqrt(v^2-(2*W)/m)',
      },
    ),
    Formula(
      id: 'hsc_spring_force',
      name: "Hooke's Law (F = Kx)",
      variables: ['F', 'K', 'x'],
      equations: {'F': 'K*x', 'K': 'F/x', 'x': 'F/K'},
    ),
    Formula(
      id: 'hsc_spring_work',
      name: 'Work in Spring (W = ½K(x2²-x1²))',
      variables: ['W', 'K', 'x1', 'x2'],
      equations: {
        'W': '0.5*K*(x2^2-x1^2)',
        'K': '(2*W)/(x2^2-x1^2)',
        'x1': 'sqrt(x2^2-(2*W)/K)',
        'x2': 'sqrt(x1^2+(2*W)/K)',
      },
    ),
    Formula(
      id: 'hsc_elastic_pe',
      name: 'Elastic Potential Energy (W = ½Kx²)',
      variables: ['W', 'K', 'x'],
      equations: {'W': '0.5*K*x^2', 'K': '(2*W)/(x^2)', 'x': 'sqrt(2*W/K)'},
    ),
    Formula(
      id: 'hsc_gravitational_force',
      name: 'Gravitational Force (F = GMm/R²)',
      variables: ['F', 'G', 'M', 'm', 'R'],
      equations: {
        'F': 'G*M*m/(R^2)',
        'G': 'F*R^2/(M*m)',
        'M': 'F*R^2/(G*m)',
        'm': 'F*R^2/(G*M)',
        'R': 'sqrt(G*M*m/F)',
      },
    ),
    Formula(
      id: 'hsc_work_gravity',
      name: 'Work against Gravity (W = mgh)',
      variables: ['W', 'm', 'g', 'h'],
      equations: {'W': 'm*g*h', 'm': 'W/(g*h)', 'g': 'W/(m*h)', 'h': 'W/(m*g)'},
    ),
    Formula(
      id: 'hsc_work_incline',
      name: 'Work on Inclined Plane (W = mgs·sinα)',
      variables: ['W', 'm', 'g', 's', 'alpha'],
      equations: {
        'W': 'm*g*s*sin(alpha)',
        'm': 'W/(g*s*sin(alpha))',
        'g': 'W/(m*s*sin(alpha))',
        's': 'W/(m*g*sin(alpha))',
        'alpha': 'asin(W/(m*g*s))',
      },
    ),
    Formula(
      id: 'hsc_grav_pe_universal',
      name: 'Universal Gravitational PE (U = -GMm/r)',
      variables: ['U', 'G', 'M', 'm', 'r'],
      equations: {
        'U': '-G*M*m/r',
        'G': '-U*r/(M*m)',
        'M': '-U*r/(G*m)',
        'm': '-U*r/(G*M)',
        'r': '-G*M*m/U',
      },
    ),
    Formula(
      id: 'hsc_work_between_radii',
      name: 'Work between Radii (W = -GMm(1/rb - 1/ra))',
      variables: ['W', 'G', 'M', 'm', 'ra', 'rb'],
      equations: {
        'W': '-G*M*m*(1/rb-1/ra)',
        'rb': '1/((1/ra)-(W/(G*M*m)))',
        'ra': '1/((1/rb)+(W/(G*M*m)))',
      },
    ),
    Formula(
      id: 'hsc_work_rotational',
      name: 'Rotational Work (W = τθ)',
      variables: ['W', 'tau', 'theta'],
      equations: {'W': 'tau*theta', 'tau': 'W/theta', 'theta': 'W/tau'},
    ),
    Formula(
      id: 'hsc_work_n_rotations',
      name: 'Work for N Rotations (W = 2πnτ)',
      variables: ['W', 'n', 'tau'],
      equations: {
        'W': '2*3.14159*n*tau',
        'n': 'W/(2*3.14159*tau)',
        'tau': 'W/(2*3.14159*n)',
      },
    ),
    Formula(
      id: 'hsc_kinetic_energy',
      name: 'Kinetic Energy (Ek = ½mv²)',
      variables: ['Ek', 'm', 'v'],
      equations: {'Ek': '0.5*m*v^2', 'm': '2*Ek/(v^2)', 'v': 'sqrt(2*Ek/m)'},
    ),
    Formula(
      id: 'hsc_ke_momentum',
      name: 'Kinetic Energy from Momentum (Ek = P²/2m)',
      variables: ['Ek', 'P', 'm'],
      equations: {'Ek': 'P^2/(2*m)', 'P': 'sqrt(2*m*Ek)', 'm': 'P^2/(2*Ek)'},
    ),
    Formula(
      id: 'hsc_grav_pe',
      name: 'Gravitational PE (Ep = mgh)',
      variables: ['Ep', 'm', 'g', 'h'],
      equations: {
        'Ep': 'm*g*h',
        'm': 'Ep/(g*h)',
        'g': 'Ep/(m*h)',
        'h': 'Ep/(m*g)',
      },
    ),
    Formula(
      id: 'hsc_spring_period_ch5',
      name: 'Spring-Mass Period (T = 2π√(m/K))',
      variables: ['T', 'm', 'K'],
      equations: {
        'T': '2*3.14159*sqrt(m/K)',
        'm': 'K*(T/(2*3.14159))^2',
        'K': 'm/((T/(2*3.14159))^2)',
      },
    ),

    // ========== CHAPTER 6: GRAVITATION ==========
    Formula(
      id: 'hsc_grav_force_newton',
      name: "Newton's Law of Gravitation (F = Gm1m2/d²)",
      variables: ['F', 'G', 'm1', 'm2', 'd'],
      equations: {
        'F': 'G*m1*m2/(d^2)',
        'G': 'F*d^2/(m1*m2)',
        'm1': 'F*d^2/(G*m2)',
        'm2': 'F*d^2/(G*m1)',
        'd': 'sqrt(G*m1*m2/F)',
      },
    ),
    Formula(
      id: 'hsc_weight',
      name: 'Weight (W = mg)',
      variables: ['W', 'm', 'g'],
      equations: {'W': 'm*g', 'm': 'W/g', 'g': 'W/m'},
    ),
    Formula(
      id: 'hsc_orbital_velocity',
      name: 'Orbital Velocity (v = √(GM/r))',
      variables: ['v', 'G', 'M', 'r'],
      equations: {
        'v': 'sqrt(G*M/r)',
        'G': 'v^2*r/M',
        'M': 'v^2*r/G',
        'r': 'G*M/(v^2)',
      },
    ),
    Formula(
      id: 'hsc_kepler3',
      name: "Kepler's 3rd Law (T² = (4π²/GM)r³)",
      variables: ['T', 'G', 'M', 'r'],
      equations: {
        'T': 'sqrt((4*3.14159^2/G/M)*r^3)',
        'G': '(4*3.14159^2*r^3)/(M*T^2)',
        'M': '(4*3.14159^2*r^3)/(G*T^2)',
        'r': '((G*M*T^2)/(4*3.14159^2))^(1/3)',
      },
    ),
    Formula(
      id: 'hsc_mass_of_sun',
      name: 'Mass of Central Body (M = 4π²r³/GT²)',
      variables: ['M', 'r', 'G', 'T'],
      equations: {
        'M': '(4*3.14159^2*r^3)/(G*T^2)',
        'r': '((M*G*T^2)/(4*3.14159^2))^(1/3)',
        'G': '(4*3.14159^2*r^3)/(M*T^2)',
        'T': 'sqrt((4*3.14159^2*r^3)/(G*M))',
      },
    ),
    Formula(
      id: 'hsc_g_surface',
      name: "g at Earth's Surface (g = GM/R²)",
      variables: ['g', 'G', 'M', 'R'],
      equations: {
        'g': 'G*M/(R^2)',
        'G': 'g*R^2/M',
        'M': 'g*R^2/G',
        'R': 'sqrt(G*M/g)',
      },
    ),
    Formula(
      id: 'hsc_g_density',
      name: 'g from Average Density (g = (4/3)πGRρ)',
      variables: ['g', 'G', 'R', 'rho'],
      equations: {
        'g': '(4/3)*3.14159*G*R*rho',
        'G': '3*g/(4*3.14159*R*rho)',
        'R': '3*g/(4*3.14159*G*rho)',
        'rho': '3*g/(4*3.14159*G*R)',
      },
    ),
    Formula(
      id: 'hsc_mass_earth',
      name: 'Mass of Earth (M = gR²/G)',
      variables: ['M', 'g', 'R', 'G'],
      equations: {
        'M': 'g*R^2/G',
        'g': 'M*G/(R^2)',
        'R': 'sqrt(M*G/g)',
        'G': 'g*R^2/M',
      },
    ),
    Formula(
      id: 'hsc_earth_density',
      name: "Earth's Average Density (ρ = 3g/4πGR)",
      variables: ['rho', 'g', 'G', 'R'],
      equations: {
        'rho': '3*g/(4*3.14159*G*R)',
        'g': '4*3.14159*G*R*rho/3',
        'G': '3*g/(4*3.14159*R*rho)',
        'R': '3*g/(4*3.14159*G*rho)',
      },
    ),
    Formula(
      id: 'hsc_g_height_general',
      name: 'g at Height h (gₕ = GM/(R+h)²)',
      variables: ['gh', 'G', 'M', 'R', 'h'],
      equations: {
        'gh': 'G*M/((R+h)^2)',
        'G': 'gh*(R+h)^2/M',
        'M': 'gh*(R+h)^2/G',
        'h': 'sqrt(G*M/gh)-R',
      },
    ),
    Formula(
      id: 'hsc_g_height_ratio',
      name: 'g at Height Ratio (gₕ = gR²/(R+h)²)',
      variables: ['gh', 'g', 'R', 'h'],
      equations: {
        'gh': 'g*R^2/((R+h)^2)',
        'g': 'gh*(R+h)^2/(R^2)',
        'h': 'R*(sqrt(g/gh)-1)',
      },
    ),
    Formula(
      id: 'hsc_g_height_approx',
      name: 'g at Height (approx h << R): gₕ = g(1-2h/R)',
      variables: ['gh', 'g', 'h', 'R'],
      equations: {
        'gh': 'g*(1-2*h/R)',
        'g': 'gh/(1-2*h/R)',
        'h': '((1-gh/g)*R)/2',
        'R': '2*h/(1-gh/g)',
      },
    ),
    Formula(
      id: 'hsc_g_depth',
      name: 'g at Depth h (gₕ = g(1-h/R))',
      variables: ['gh', 'g', 'h', 'R'],
      equations: {
        'gh': 'g*(1-h/R)',
        'g': 'gh/(1-h/R)',
        'h': '(1-gh/g)*R',
        'R': 'h/(1-gh/g)',
      },
    ),
    Formula(
      id: 'hsc_g_latitude',
      name: 'g at Latitude (g\' = g - ω²Rcos²λ)',
      variables: ['gp', 'g', 'omega', 'R', 'lambda'],
      equations: {
        'gp': 'g-omega^2*R*(cos(lambda))^2',
        'g': 'gp+omega^2*R*(cos(lambda))^2',
        'omega': 'sqrt((g-gp)/(R*(cos(lambda))^2))',
        'R': '(g-gp)/(omega^2*(cos(lambda))^2)',
        'lambda': 'acos(sqrt((g-gp)/(omega^2*R)))',
      },
    ),
    Formula(
      id: 'hsc_field_intensity',
      name: 'Gravitational Field Intensity (E = F/m)',
      variables: ['E', 'F', 'm'],
      equations: {'E': 'F/m', 'F': 'E*m', 'm': 'F/E'},
    ),
    Formula(
      id: 'hsc_field_point_mass',
      name: 'Field from Point Mass (E = GM/r²)',
      variables: ['E', 'G', 'M', 'r'],
      equations: {
        'E': 'G*M/(r^2)',
        'G': 'E*r^2/M',
        'M': 'E*r^2/G',
        'r': 'sqrt(G*M/E)',
      },
    ),
    Formula(
      id: 'hsc_grav_potential',
      name: 'Gravitational Potential (V = W/m)',
      variables: ['V', 'W', 'm'],
      equations: {'V': 'W/m', 'W': 'V*m', 'm': 'W/V'},
    ),
    Formula(
      id: 'hsc_grav_potential_point',
      name: 'Gravitational Potential (V = -GM/r)',
      variables: ['V', 'G', 'M', 'r'],
      equations: {'V': '-G*M/r', 'G': '-V*r/M', 'M': '-V*r/G', 'r': '-G*M/V'},
    ),
    Formula(
      id: 'hsc_grav_pe_universal_c6',
      name: 'Gravitational PE (U = -GMm/r)',
      variables: ['U', 'G', 'M', 'm', 'r'],
      equations: {
        'U': '-G*M*m/r',
        'G': '-U*r/(M*m)',
        'M': '-U*r/(G*m)',
        'm': '-U*r/(G*M)',
        'r': '-G*M*m/U',
      },
    ),
    Formula(
      id: 'hsc_inside_sphere_potential',
      name: 'Potential Inside Solid Sphere',
      variables: ['V', 'G', 'M', 'a', 'r'],
      equations: {'V': '-G*M*(3*a^2-r^2)/(2*a^3)'},
    ),
    Formula(
      id: 'hsc_inside_sphere_field',
      name: 'Field Inside Solid Sphere (E = GMr/a³)',
      variables: ['E', 'G', 'M', 'a', 'r'],
      equations: {
        'E': 'G*M*r/(a^3)',
        'G': 'E*a^3/(M*r)',
        'M': 'E*a^3/(G*r)',
        'a': '(G*M*r/E)^(1/3)',
        'r': 'E*a^3/(G*M)',
      },
    ),
    Formula(
      id: 'hsc_hollow_sphere_potential',
      name: 'Potential Inside Hollow Sphere (V = -GM/a)',
      variables: ['V', 'G', 'M', 'a'],
      equations: {'V': '-G*M/a', 'G': '-V*a/M', 'M': '-V*a/G', 'a': '-G*M/V'},
    ),
    Formula(
      id: 'hsc_max_height_projected',
      name: 'Max Height of Projected Body',
      variables: ['r', 'g', 'R', 'v'],
      equations: {
        'r': '2*g*R^2/(2*g*R-v^2)',
        'g': '(v^2*r)/(2*R*(r-R))',
        'R': 'sqrt(v^2*r/(2*g*(r-1)))',
        'v': 'sqrt(2*g*R-2*g*R^2/r)',
      },
    ),
    Formula(
      id: 'hsc_escape_velocity_M',
      name: 'Escape Velocity (vₑ = √(2GM/R))',
      variables: ['ve', 'G', 'M', 'R'],
      equations: {
        've': 'sqrt(2*G*M/R)',
        'G': 've^2*R/(2*M)',
        'M': 've^2*R/(2*G)',
        'R': '2*G*M/(ve^2)',
      },
    ),
    Formula(
      id: 'hsc_escape_velocity_gR',
      name: 'Escape Velocity (vₑ = √(2gR))',
      variables: ['ve', 'g', 'R'],
      equations: {'ve': 'sqrt(2*g*R)', 'g': 've^2/(2*R)', 'R': 've^2/(2*g)'},
    ),

    // ========== CHAPTER 7: STRUCTURAL PROPERTIES OF MATTER ==========
    Formula(
      id: 'hsc_breaking_stress',
      name: 'Breaking Stress (σ = F/A)',
      variables: ['sigma', 'F', 'A'],
      equations: {'sigma': 'F/A', 'F': 'sigma*A', 'A': 'F/sigma'},
    ),
    Formula(
      id: 'hsc_longitudinal_strain',
      name: 'Longitudinal Strain (ε = l/L)',
      variables: ['epsilon', 'l', 'L'],
      equations: {'epsilon': 'l/L', 'l': 'epsilon*L', 'L': 'l/epsilon'},
    ),
    Formula(
      id: 'hsc_shearing_strain',
      name: 'Shearing Strain (θ = d/D)',
      variables: ['theta', 'd', 'D'],
      equations: {'theta': 'd/D', 'd': 'theta*D', 'D': 'd/theta'},
    ),
    Formula(
      id: 'hsc_volume_strain',
      name: 'Volume Strain (εv = v/V)',
      variables: ['epsilonv', 'v', 'V'],
      equations: {'epsilonv': 'v/V', 'v': 'epsilonv*V', 'V': 'v/epsilonv'},
    ),
    Formula(
      id: 'hsc_youngs_modulus',
      name: "Young's Modulus (Y = FL/(Al))",
      variables: ['Y', 'F', 'L', 'A', 'l'],
      equations: {
        'Y': 'F*L/(A*l)',
        'F': 'Y*A*l/L',
        'L': 'Y*A*l/F',
        'A': 'F*L/(Y*l)',
        'l': 'F*L/(A*Y)',
      },
    ),
    Formula(
      id: 'hsc_rigidity_modulus',
      name: 'Rigidity Modulus (n = F/(Aθ))',
      variables: ['n', 'F', 'A', 'theta'],
      equations: {
        'n': 'F/(A*theta)',
        'F': 'n*A*theta',
        'A': 'F/(n*theta)',
        'theta': 'F/(A*n)',
      },
    ),
    Formula(
      id: 'hsc_bulk_modulus',
      name: 'Bulk Modulus (K = PV/v)',
      variables: ['K', 'P', 'V', 'v'],
      equations: {'K': 'P*V/v', 'P': 'K*v/V', 'V': 'K*v/P', 'v': 'P*V/K'},
    ),
    Formula(
      id: 'hsc_compressibility',
      name: 'Compressibility (C = v/(PV))',
      variables: ['C', 'v', 'P', 'V'],
      equations: {'C': 'v/(P*V)', 'v': 'C*P*V', 'P': 'v/(C*V)', 'V': 'v/(C*P)'},
    ),
    Formula(
      id: 'hsc_work_wire',
      name: 'Work in Wire Elongation (W = ½Fl)',
      variables: ['W', 'F', 'l'],
      equations: {'W': '0.5*F*l', 'F': '2*W/l', 'l': '2*W/F'},
    ),
    Formula(
      id: 'hsc_energy_density_long',
      name: 'Energy Density (Longitudinal)',
      variables: ['u', 'Y', 'l', 'L'],
      equations: {
        'u': '0.5*Y*(l/L)^2',
        'Y': '2*u/((l/L)^2)',
        'l': 'L*sqrt(2*u/Y)',
        'L': 'l/sqrt(2*u/Y)',
      },
    ),
    Formula(
      id: 'hsc_energy_density_vol',
      name: 'Energy Density (Volume Strain)',
      variables: ['u', 'K', 'v', 'V'],
      equations: {
        'u': '0.5*K*(v/V)^2',
        'K': '2*u/((v/V)^2)',
        'v': 'V*sqrt(2*u/K)',
        'V': 'v/sqrt(2*u/K)',
      },
    ),
    Formula(
      id: 'hsc_energy_density_shear',
      name: 'Energy Density (Shearing)',
      variables: ['u', 'n', 'theta'],
      equations: {
        'u': '0.5*n*theta^2',
        'n': '2*u/(theta^2)',
        'theta': 'sqrt(2*u/n)',
      },
    ),
    Formula(
      id: 'hsc_spring_force_elasticity',
      name: 'Spring Force (F = Kx)',
      variables: ['F', 'K', 'x'],
      equations: {'F': 'K*x', 'K': 'F/x', 'x': 'F/K'},
    ),
    Formula(
      id: 'hsc_series_springs',
      name: 'Series Springs (Keq = K1K2/(K1+K2))',
      variables: ['Keq', 'K1', 'K2'],
      equations: {
        'Keq': 'K1*K2/(K1+K2)',
        'K1': 'Keq*K2/(K2-Keq)',
        'K2': 'Keq*K1/(K1-Keq)',
      },
    ),
    Formula(
      id: 'hsc_parallel_springs',
      name: 'Parallel Springs (Keq = K1 + K2)',
      variables: ['Keq', 'K1', 'K2'],
      equations: {'Keq': 'K1+K2', 'K1': 'Keq-K2', 'K2': 'Keq-K1'},
    ),
    Formula(
      id: 'hsc_spring_pe',
      name: 'Potential Energy of Spring (E = ½Kx²)',
      variables: ['E', 'K', 'x'],
      equations: {'E': '0.5*K*x^2', 'K': '2*E/(x^2)', 'x': 'sqrt(2*E/K)'},
    ),
    Formula(
      id: 'hsc_poisson_ratio',
      name: "Poisson's Ratio (σ = -LΔr/(rl))",
      variables: ['sigma', 'L', 'dr', 'r', 'l'],
      equations: {
        'sigma': '-L*dr/(r*l)',
        'L': '-sigma*r*l/dr',
        'dr': '-sigma*r*l/L',
        'r': '-L*dr/(sigma*l)',
        'l': '-L*dr/(r*sigma)',
      },
    ),
    Formula(
      id: 'hsc_y_3k_sigma',
      name: "Relation Y = 3K(1-2σ)",
      variables: ['Y', 'K', 'sigma'],
      equations: {
        'Y': '3*K*(1-2*sigma)',
        'K': 'Y/(3*(1-2*sigma))',
        'sigma': '(1-Y/(3*K))/2',
      },
    ),
    Formula(
      id: 'hsc_y_2n_sigma',
      name: 'Relation Y = 2n(1+σ)',
      variables: ['Y', 'n', 'sigma'],
      equations: {
        'Y': '2*n*(1+sigma)',
        'n': 'Y/(2*(1+sigma))',
        'sigma': 'Y/(2*n)-1',
      },
    ),
    Formula(
      id: 'hsc_sigma_from_k_n',
      name: 'σ = (3K-2n)/(6K+2n)',
      variables: ['sigma', 'K', 'n'],
      equations: {'sigma': '(3*K-2*n)/(6*K+2*n)'},
    ),
    Formula(
      id: 'hsc_nine_y_relation',
      name: 'Relation 9/Y = 1/K + 3/n',
      variables: ['Y', 'K', 'n'],
      equations: {'Y': '9/((1/K)+(3/n))'},
    ),
    Formula(
      id: 'hsc_volume_strain_poisson',
      name: 'Volume Strain (dV/V = e(1-2σ))',
      variables: ['dV', 'V', 'e', 'sigma'],
      equations: {
        'dV': 'V*e*(1-2*sigma)',
        'V': 'dV/(e*(1-2*sigma))',
        'e': 'dV/(V*(1-2*sigma))',
        'sigma': '(1-dV/(V*e))/2',
      },
    ),

    // ========== CHAPTER 8: PERIODIC MOTION (SHM) ==========
    Formula(
      id: 'hsc_shm_displacement',
      name: 'SHM Displacement (x = A·sin(ωt + δ))',
      variables: ['x', 'A', 'omega', 't', 'delta'],
      equations: {
        'x': 'A*sin(omega*t+delta)',
        'A': 'x/sin(omega*t+delta)',
        'omega': '(asin(x/A)-delta)/t',
        't': '(asin(x/A)-delta)/omega',
        'delta': 'asin(x/A)-omega*t',
      },
    ),
    Formula(
      id: 'hsc_shm_acceleration',
      name: 'SHM Acceleration (a = -ω²x)',
      variables: ['a', 'omega', 'x'],
      equations: {
        'a': '-omega^2*x',
        'omega': 'sqrt(-a/x)',
        'x': '-a/(omega^2)',
      },
    ),
    Formula(
      id: 'hsc_shm_restoring_force',
      name: 'Restoring Force (F = -Kx)',
      variables: ['F', 'K', 'x'],
      equations: {'F': '-K*x', 'K': '-F/x', 'x': '-F/K'},
    ),
    Formula(
      id: 'hsc_shm_velocity_disp',
      name: 'SHM Velocity from Displacement (v = ω√(A²-x²))',
      variables: ['v', 'omega', 'A', 'x'],
      equations: {
        'v': 'omega*sqrt(A^2-x^2)',
        'omega': 'v/sqrt(A^2-x^2)',
        'A': 'sqrt((v/omega)^2+x^2)',
        'x': 'sqrt(A^2-(v/omega)^2)',
      },
    ),
    Formula(
      id: 'hsc_shm_velocity_time',
      name: 'SHM Velocity from Time (v = Aω·cos(ωt+δ))',
      variables: ['v', 'A', 'omega', 't', 'delta'],
      equations: {
        'v': 'A*omega*cos(omega*t+delta)',
        'A': 'v/(omega*cos(omega*t+delta))',
        'omega': 'v/(A*cos(omega*t+delta))',
        't': '(acos(v/(A*omega))-delta)/omega',
        'delta': 'acos(v/(A*omega))-omega*t',
      },
    ),
    Formula(
      id: 'hsc_shm_period',
      name: 'SHM Period (T = 2π√(m/K))',
      variables: ['T', 'm', 'K'],
      equations: {
        'T': '2*3.14159*sqrt(m/K)',
        'm': 'K*(T/(2*3.14159))^2',
        'K': 'm/((T/(2*3.14159))^2)',
      },
    ),
    Formula(
      id: 'hsc_shm_frequency',
      name: 'SHM Frequency (n = (1/2π)√(K/m))',
      variables: ['n', 'K', 'm'],
      equations: {
        'n': '(1/(2*3.14159))*sqrt(K/m)',
        'K': 'm*(2*3.14159*n)^2',
        'm': 'K/((2*3.14159*n)^2)',
      },
    ),
    Formula(
      id: 'hsc_shm_angular_freq',
      name: 'Angular Frequency (ω = √(K/m))',
      variables: ['omega', 'K', 'm'],
      equations: {'omega': 'sqrt(K/m)', 'K': 'm*omega^2', 'm': 'K/(omega^2)'},
    ),
    Formula(
      id: 'hsc_height_mountain',
      name: 'Height of Mountain (h = R(T1/T - 1))',
      variables: ['h', 'R', 'T1', 'T'],
      equations: {
        'h': 'R*(T1/T-1)',
        'R': 'h/(T1/T-1)',
        'T1': 'T*(h/R+1)',
        'T': 'T1/(h/R+1)',
      },
    ),
    Formula(
      id: 'hsc_clock_correction',
      name: 'Pendulum Clock Correction (T\' = 2×86400/(86400+n))',
      variables: ['Tp', 'n'],
      equations: {'Tp': '2*86400/(86400+n)', 'n': '2*86400/Tp-86400'},
    ),
    Formula(
      id: 'hsc_shm_ke',
      name: 'SHM Kinetic Energy (Ek = ½mω²(A²-x²))',
      variables: ['Ek', 'm', 'omega', 'A', 'x'],
      equations: {
        'Ek': '0.5*m*omega^2*(A^2-x^2)',
        'm': '2*Ek/(omega^2*(A^2-x^2))',
        'omega': 'sqrt(2*Ek/(m*(A^2-x^2)))',
        'A': 'sqrt(x^2+2*Ek/(m*omega^2))',
        'x': 'sqrt(A^2-2*Ek/(m*omega^2))',
      },
    ),
    Formula(
      id: 'hsc_shm_pe',
      name: 'SHM Potential Energy (Ep = ½mω²x²)',
      variables: ['Ep', 'm', 'omega', 'x'],
      equations: {
        'Ep': '0.5*m*omega^2*x^2',
        'm': '2*Ep/(omega^2*x^2)',
        'omega': 'sqrt(2*Ep/(m*x^2))',
        'x': 'sqrt(2*Ep/(m*omega^2))',
      },
    ),
    Formula(
      id: 'hsc_shm_total_energy',
      name: 'SHM Total Energy (E = ½mω²A²)',
      variables: ['E', 'm', 'omega', 'A'],
      equations: {
        'E': '0.5*m*omega^2*A^2',
        'm': '2*E/(omega^2*A^2)',
        'omega': 'sqrt(2*E/(m*A^2))',
        'A': 'sqrt(2*E/(m*omega^2))',
      },
    ),
    Formula(
      id: 'hsc_utube_period',
      name: 'U-Tube Liquid Column Period (T = 2π√(L/g))',
      variables: ['T', 'L', 'g'],
      equations: {
        'T': '2*3.14159*sqrt(L/g)',
        'L': 'g*(T/(2*3.14159))^2',
        'g': 'L/((T/(2*3.14159))^2)',
      },
    ),

    // ========== CHAPTER 9: WAVES ==========
    Formula(
      id: 'hsc_wave_frequency',
      name: 'Wave Frequency (n = N/t)',
      variables: ['n', 'N', 't'],
      equations: {'n': 'N/t', 'N': 'n*t', 't': 'N/n'},
    ),
    Formula(
      id: 'hsc_wave_distance',
      name: 'Wave Distance (s = Nλ)',
      variables: ['s', 'N', 'lambda'],
      equations: {'s': 'N*lambda', 'N': 's/lambda', 'lambda': 's/N'},
    ),
    Formula(
      id: 'hsc_wave_number',
      name: 'Wave Number (ν̄ = 1/λ)',
      variables: ['nu', 'lambda'],
      equations: {'nu': '1/lambda', 'lambda': '1/nu'},
    ),
    Formula(
      id: 'hsc_wave_period',
      name: 'Wave Time Period (T = t/N)',
      variables: ['T', 't', 'N'],
      equations: {'T': 't/N', 't': 'T*N', 'N': 't/T'},
    ),
    Formula(
      id: 'hsc_wave_speed',
      name: 'Wave Speed (v = nλ)',
      variables: ['v', 'n', 'lambda'],
      equations: {'v': 'n*lambda', 'n': 'v/lambda', 'lambda': 'v/n'},
    ),
    Formula(
      id: 'hsc_progressive_wave',
      name: 'Progressive Wave (y = a·sin(2π(vt-x)/λ))',
      variables: ['y', 'a', 'v', 't', 'x', 'lambda'],
      equations: {
        'y': 'a*sin(2*3.14159*(v*t-x)/lambda)',
        'a': 'y/sin(2*3.14159*(v*t-x)/lambda)',
      },
    ),
    Formula(
      id: 'hsc_phase_angle',
      name: 'Phase Angle (θ = 2π(vt-x)/λ)',
      variables: ['theta', 'v', 't', 'x', 'lambda'],
      equations: {
        'theta': '2*3.14159*(v*t-x)/lambda',
        'v': '(theta*lambda/(2*3.14159)+x)/t',
        't': '(theta*lambda/(2*3.14159)+x)/v',
        'x': 'v*t-theta*lambda/(2*3.14159)',
        'lambda': '2*3.14159*(v*t-x)/theta',
      },
    ),
    Formula(
      id: 'hsc_phase_path_diff',
      name: 'Phase Difference (Δθ = 2πΔx/λ)',
      variables: ['dtheta', 'dx', 'lambda'],
      equations: {
        'dtheta': '2*3.14159*dx/lambda',
        'dx': 'dtheta*lambda/(2*3.14159)',
        'lambda': '2*3.14159*dx/dtheta',
      },
    ),
    Formula(
      id: 'hsc_stationary_wave',
      name: 'Stationary Wave (y = 2a·cos(2πx/λ)sin(2πvt/λ))',
      variables: ['y', 'a', 'x', 'v', 't', 'lambda'],
      equations: {
        'y': '2*a*cos(2*3.14159*x/lambda)*sin(2*3.14159*v*t/lambda)',
        'a': 'y/(2*cos(2*3.14159*x/lambda)*sin(2*3.14159*v*t/lambda))',
      },
    ),
    Formula(
      id: 'hsc_antinode_pos',
      name: 'Antinode Position (x = (2n+1)λ/4)',
      variables: ['x', 'n', 'lambda'],
      equations: {
        'x': '(2*n+1)*lambda/4',
        'n': '(4*x/lambda-1)/2',
        'lambda': '4*x/(2*n+1)',
      },
    ),
    Formula(
      id: 'hsc_node_pos',
      name: 'Node Position (x = nλ/2)',
      variables: ['x', 'n', 'lambda'],
      equations: {'x': 'n*lambda/2', 'n': '2*x/lambda', 'lambda': '2*x/n'},
    ),
    Formula(
      id: 'hsc_node_node_dist',
      name: 'Distance Between Two Nodes (d = λ/2)',
      variables: ['d', 'lambda'],
      equations: {'d': 'lambda/2', 'lambda': '2*d'},
    ),
    Formula(
      id: 'hsc_node_antinode_dist',
      name: 'Distance Node-Antinode (d = λ/4)',
      variables: ['d', 'lambda'],
      equations: {'d': 'lambda/4', 'lambda': '4*d'},
    ),
    Formula(
      id: 'hsc_melde_transverse',
      name: "Melde's Transverse (N = (1/λ)√(Mg/m))",
      variables: ['N', 'lambda', 'M', 'g', 'm'],
      equations: {
        'N': '(1/lambda)*sqrt(M*g/m)',
        'lambda': 'sqrt(M*g/m)/N',
        'M': 'm*(N*lambda)^2/g',
        'g': 'm*(N*lambda)^2/M',
        'm': 'M*g/(N*lambda)^2',
      },
    ),
    Formula(
      id: 'hsc_melde_longitudinal',
      name: "Melde's Longitudinal (N = (2/λ)√(Mg/m))",
      variables: ['N', 'lambda', 'M', 'g', 'm'],
      equations: {
        'N': '(2/lambda)*sqrt(M*g/m)',
        'lambda': '2*sqrt(M*g/m)/N',
        'M': 'm*(N*lambda)^2/(4*g)',
        'g': 'm*(N*lambda)^2/(4*M)',
        'm': '4*M*g/(N*lambda)^2',
      },
    ),
    Formula(
      id: 'hsc_sound_intensity_inverse_square',
      name: 'Sound Intensity (I = P/(4πr²))',
      variables: ['I', 'P', 'r'],
      equations: {
        'I': 'P/(4*3.14159*r^2)',
        'P': 'I*4*3.14159*r^2',
        'r': 'sqrt(P/(4*3.14159*I))',
      },
    ),
    Formula(
      id: 'hsc_wave_energy_density',
      name: 'Wave Energy Density (E = ½ρA²ω²)',
      variables: ['E', 'rho', 'A', 'omega'],
      equations: {
        'E': '0.5*rho*A^2*omega^2',
        'rho': '2*E/(A^2*omega^2)',
        'A': 'sqrt(2*E/(rho*omega^2))',
        'omega': 'sqrt(2*E/(rho*A^2))',
      },
    ),
    Formula(
      id: 'hsc_wave_intensity',
      name: 'Wave Intensity (I = ½ρA²ω²v)',
      variables: ['I', 'rho', 'A', 'omega', 'v'],
      equations: {
        'I': '0.5*rho*A^2*omega^2*v',
        'rho': '2*I/(A^2*omega^2*v)',
        'A': 'sqrt(2*I/(rho*omega^2*v))',
        'omega': 'sqrt(2*I/(rho*A^2*v))',
        'v': '2*I/(rho*A^2*omega^2)',
      },
    ),
    Formula(
      id: 'hsc_db_level',
      name: 'Sound Level (β = 10·log(I/I0))',
      variables: ['beta', 'I', 'I0'],
      equations: {
        'beta': '10*log(I/I0)',
        'I': 'I0*10^(beta/10)',
        'I0': 'I/(10^(beta/10))',
      },
    ),

    // ========== CHAPTER 10: GAS LAWS & KINETIC THEORY ==========
    Formula(
      id: 'hsc_boyles_law',
      name: "Boyle's Law (P1V1 = P2V2)",
      variables: ['P1', 'V1', 'P2', 'V2'],
      equations: {
        'P1': 'P2*V2/V1',
        'V1': 'P2*V2/P1',
        'P2': 'P1*V1/V2',
        'V2': 'P1*V1/P2',
      },
    ),
    Formula(
      id: 'hsc_charles_law',
      name: "Charles's Law (V1/T1 = V2/T2)",
      variables: ['V1', 'T1', 'V2', 'T2'],
      equations: {
        'V1': 'V2*T1/T2',
        'T1': 'V1*T2/V2',
        'V2': 'V1*T2/T1',
        'T2': 'V2*T1/V1',
      },
    ),
    Formula(
      id: 'hsc_pressure_law',
      name: "Pressure Law (P1/T1 = P2/T2)",
      variables: ['P1', 'T1', 'P2', 'T2'],
      equations: {
        'P1': 'P2*T1/T2',
        'T1': 'P1*T2/P2',
        'P2': 'P1*T2/T1',
        'T2': 'P2*T1/P1',
      },
    ),
    Formula(
      id: 'hsc_pressure_vs_celsius',
      name: 'Pressure vs Celsius (P = P0(1 + θ/273))',
      variables: ['P', 'P0', 'theta'],
      equations: {
        'P': 'P0*(1+theta/273)',
        'P0': 'P/(1+theta/273)',
        'theta': '(P/P0-1)*273',
      },
    ),
    Formula(
      id: 'hsc_volume_vs_celsius',
      name: 'Volume vs Celsius (V = V0(1 + θ/273))',
      variables: ['V', 'V0', 'theta'],
      equations: {
        'V': 'V0*(1+theta/273)',
        'V0': 'V/(1+theta/273)',
        'theta': '(V/V0-1)*273',
      },
    ),
    Formula(
      id: 'hsc_combined_gas',
      name: 'Combined Gas Law (P1V1/T1 = P2V2/T2)',
      variables: ['P1', 'V1', 'T1', 'P2', 'V2', 'T2'],
      equations: {
        'P1': 'P2*V2*T1/(V1*T2)',
        'V1': 'P2*V2*T1/(P1*T2)',
        'T1': 'P1*V1*T2/(P2*V2)',
        'P2': 'P1*V1*T2/(V2*T1)',
        'V2': 'P1*V1*T2/(P2*T1)',
        'T2': 'P2*V2*T1/(P1*V1)',
      },
    ),
    Formula(
      id: 'hsc_ideal_gas',
      name: 'Ideal Gas (PV = nRT)',
      variables: ['P', 'V', 'n', 'T'],
      equations: {
        'P': 'n*8.314*T/V',
        'V': 'n*8.314*T/P',
        'n': 'P*V/(8.314*T)',
        'T': 'P*V/(n*8.314)',
      },
    ),
    Formula(
      id: 'hsc_moles',
      name: 'Number of Moles (n = m/M)',
      variables: ['n', 'm', 'M'],
      equations: {'n': 'm/M', 'm': 'n*M', 'M': 'm/n'},
    ),
    Formula(
      id: 'hsc_gas_density',
      name: 'Gas Density Relation (P1/(ρ1T1) = P2/(ρ2T2))',
      variables: ['P1', 'rho1', 'T1', 'P2', 'rho2', 'T2'],
      equations: {
        'P1': 'P2*rho1*T1/(rho2*T2)',
        'rho1': 'P1*rho2*T2/(P2*T1)',
        'T1': 'P1*rho2*T2/(P2*rho1)',
        'P2': 'P1*rho2*T2/(rho1*T1)',
        'rho2': 'P2*rho1*T1/(P1*T2)',
        'T2': 'P2*rho1*T1/(P1*rho2)',
      },
    ),
    Formula(
      id: 'hsc_density_const_pressure',
      name: 'Density at Constant Pressure (ρ1T1 = ρ2T2)',
      variables: ['rho1', 'T1', 'rho2', 'T2'],
      equations: {
        'rho1': 'rho2*T2/T1',
        'T1': 'rho2*T2/rho1',
        'rho2': 'rho1*T1/T2',
        'T2': 'rho1*T1/rho2',
      },
    ),
    Formula(
      id: 'hsc_density_const_temp',
      name: 'Density at Constant Temperature (P1/ρ1 = P2/ρ2)',
      variables: ['P1', 'rho1', 'P2', 'rho2'],
      equations: {
        'P1': 'P2*rho1/rho2',
        'rho1': 'P1*rho2/P2',
        'P2': 'P1*rho2/rho1',
        'rho2': 'P2*rho1/P1',
      },
    ),
    Formula(
      id: 'hsc_pressure_kinetic',
      name: 'Kinetic Pressure (P = ⅓ρc²)',
      variables: ['P', 'rho', 'c'],
      equations: {'P': 'rho*c^2/3', 'rho': '3*P/(c^2)', 'c': 'sqrt(3*P/rho)'},
    ),
    Formula(
      id: 'hsc_pressure_ke',
      name: 'Pressure from KE (P = ⅔·Ek/V)',
      variables: ['P', 'Ek', 'V'],
      equations: {'P': '2*Ek/(3*V)', 'Ek': '3*P*V/2', 'V': '2*Ek/(3*P)'},
    ),
    Formula(
      id: 'hsc_rms_from_p_rho',
      name: 'RMS Velocity from P, ρ (crms = √(3P/ρ))',
      variables: ['crms', 'P', 'rho'],
      equations: {
        'crms': 'sqrt(3*P/rho)',
        'P': 'crms^2*rho/3',
        'rho': '3*P/(crms^2)',
      },
    ),
    Formula(
      id: 'hsc_rms_from_t_m',
      name: 'RMS Velocity from T, M (crms = √(3RT/M))',
      variables: ['crms', 'R', 'T', 'M'],
      equations: {
        'crms': 'sqrt(3*R*T/M)',
        'R': 'crms^2*M/(3*T)',
        'T': 'crms^2*M/(3*R)',
        'M': '3*R*T/(crms^2)',
      },
    ),
    Formula(
      id: 'hsc_total_ke_mole',
      name: 'Total KE of 1 Mole (E = (3/2)RT)',
      variables: ['E', 'R', 'T'],
      equations: {'E': '1.5*R*T', 'R': '2*E/(3*T)', 'T': '2*E/(3*R)'},
    ),
    Formula(
      id: 'hsc_total_ke_n_mole',
      name: 'Total KE of n Moles (E = (3/2)nRT)',
      variables: ['E', 'n', 'R', 'T'],
      equations: {
        'E': '1.5*n*R*T',
        'n': '2*E/(3*R*T)',
        'R': '2*E/(3*n*T)',
        'T': '2*E/(3*n*R)',
      },
    ),
    Formula(
      id: 'hsc_avg_ke_molecule',
      name: 'Average KE per Molecule (E = (3/2)kT)',
      variables: ['E', 'k', 'T'],
      equations: {'E': '1.5*k*T', 'k': '2*E/(3*T)', 'T': '2*E/(3*k)'},
    ),
    Formula(
      id: 'hsc_degrees_of_freedom',
      name: 'Degrees of Freedom (f = 3x - y)',
      variables: ['f', 'x', 'y'],
      equations: {'f': '3*x-y', 'x': '(f+y)/3', 'y': '3*x-f'},
    ),
    Formula(
      id: 'hsc_energy_per_dof',
      name: 'Energy per Degree of Freedom (E = ½kT)',
      variables: ['E', 'k', 'T'],
      equations: {'E': '0.5*k*T', 'k': '2*E/T', 'T': '2*E/k'},
    ),
    Formula(
      id: 'hsc_total_internal_energy',
      name: 'Total Molecular Energy (E = (f/2)kT)',
      variables: ['E', 'f', 'k', 'T'],
      equations: {
        'E': '0.5*f*k*T',
        'f': '2*E/(k*T)',
        'k': '2*E/(f*T)',
        'T': '2*E/(f*k)',
      },
    ),
    Formula(
      id: 'hsc_gamma_relation',
      name: 'Specific Heat Ratio (γ = 1 + 2/f)',
      variables: ['gamma', 'f'],
      equations: {'gamma': '1+2/f', 'f': '2/(gamma-1)'},
    ),
    Formula(
      id: 'hsc_mfp_clausius',
      name: "Clausius Mean Free Path (λ = 1/(nπσ²))",
      variables: ['lambda', 'n', 'sigma'],
      equations: {
        'lambda': '1/(n*3.14159*sigma^2)',
        'n': '1/(lambda*3.14159*sigma^2)',
        'sigma': 'sqrt(1/(n*3.14159*lambda))',
      },
    ),
    Formula(
      id: 'hsc_mfp_maxwell',
      name: "Maxwell Mean Free Path (λ = 1/(√2·nπσ²))",
      variables: ['lambda', 'n', 'sigma'],
      equations: {
        'lambda': '1/(1.41421*n*3.14159*sigma^2)',
        'n': '1/(1.41421*lambda*3.14159*sigma^2)',
        'sigma': 'sqrt(1/(1.41421*n*3.14159*lambda))',
      },
    ),
    Formula(
      id: 'hsc_mfp_boltzmann',
      name: "Boltzmann Mean Free Path (λ = 3/(4nπσ²))",
      variables: ['lambda', 'n', 'sigma'],
      equations: {
        'lambda': '3/(4*n*3.14159*sigma^2)',
        'n': '3/(4*lambda*3.14159*sigma^2)',
        'sigma': 'sqrt(3/(4*n*3.14159*lambda))',
      },
    ),
    Formula(
      id: 'hsc_dew_point',
      name: "Glaisher's Dew Point (θ = θ1 - G(θ1-θ2))",
      variables: ['theta', 'theta1', 'theta2', 'G'],
      equations: {
        'theta': 'theta1-G*(theta1-theta2)',
        'theta1': '(theta-G*theta2)/(1-G)',
        'theta2': 'theta1-(theta1-theta)/G',
        'G': '(theta1-theta)/(theta1-theta2)',
      },
    ),
    Formula(
      id: 'hsc_relative_humidity',
      name: 'Relative Humidity (R = (f/F)×100)',
      variables: ['R', 'f', 'F'],
      equations: {'R': '(f/F)*100', 'f': 'R*F/100', 'F': 'f*100/R'},
    ),
    Formula(
      id: 'hsc_relative_humidity_mass',
      name: 'Relative Humidity by Mass (R = (m/M)×100)',
      variables: ['R', 'm', 'M'],
      equations: {'R': '(m/M)*100', 'm': 'R*M/100', 'M': 'm*100/R'},
    ),
  ];
}
